### ISSUE TITLE
Fix overlapping/crossing buildings 🏛 🏠 🏘 🏙 

### ISSUE THREAD

**Issue by maning** [OSMPH/papercut_fix#13]
![buildings](https://cloud.githubusercontent.com/assets/353700/25747941/f306ac14-31c6-11e7-8110-af40862fad88.png)
*31K overlapping/crossing buildings as of May 05, 2017*

Using [OSMLint](https://github.com/osmlab/osmlint), we found 31K overlapping buildings in the Philippines. 😱  I created a tofix task to fix this.  We need everyone to help!

1. Go to: https://osmlab.github.io/to-fix/#/task/crossingbuildinginthephilippines  
2. Grab a task and fix.
3. Changeset comment: `Fixed crossing/overlapping buildings. https://github.com/OSMPH/papercut_fix/issues/13`. Changeset source: `OSMLint, Tofix`

**Comment by govvin** [comment]
@maning , could you add a reference to this github issue on the changeset comment?

**Comment by govvin** [comment]
Kindly post particularly examples so we can dissect the issue, and find the best way they can be avoided in the future:

http://simon04.dev.openstreetmap.org/whodidit/?zoom=12&lat=14.306291517908512&lon=120.773203339448&layers=BTT

![image](https://cloud.githubusercontent.com/assets/5821688/25770345/b10a1bb2-3265-11e7-85b9-5c2ce0157c7e.png)

### Observations
* The same area was edited by the same user, at several different dates.
* Another user edited the same area, at a later date.
* One month later, another user "validated" the edits, added new tags, but did not catch or resolve the errors.

### Questions
1. A Tasking Manager was in use, why are different people still editing the same areas?
2. The original editors were using JOSM, why didn't they resolve the validation errors that was triggered before the upload?
3. Same questions for the "validator".

**Comment by govvin** [comment]
Changesets:

- https://www.openstreetmap.org/changeset/39445538
- https://www.openstreetmap.org/changeset/39550513

![image](https://cloud.githubusercontent.com/assets/5821688/25770535/b2f4894e-326a-11e7-8c6f-b2c27e8188f4.png)

#### Observations

- two different users, both using JOSM, and editing 5 days apart, edited the same area.
- about two months later, a validator using JOSM added new tags to the buildings made in the more recent changeset, but did not address the intersecting buildings issue against the older change set.

#### Questions
1. What is the Project NOAH validation process and workflow? Are they documented somewhere?

**Comment by maning** [comment]
This area looks really bad (close to the area @govvin [mentioned](https://github.com/OSMPH/papercut_fix/issues/13#issuecomment-299619179)): https://www.openstreetmap.org/#map=18/14.305746018003981/120.77387106575434

![screen shot 2017-05-06 at 18 31 36](https://cloud.githubusercontent.com/assets/353700/25772511/65ff36fa-328a-11e7-9873-3cb755450648.png)
5 overlapping buildings

![screen shot 2017-05-06 at 18 34 50](https://cloud.githubusercontent.com/assets/353700/25772526/dfb9ddb0-328a-11e7-8a49-b5f3b8254ee2.png)
No existing buildings in Bing/Mapbox

@schadow1, I see your edits as V2 in some of these building by adding building=house and addr tags.  Any reason why overlaps were not fixed?

**Comment by maning** [comment]
> could you add a reference to this github issue on the default changeset comment?

Trying to update but there is an issue with updating changeset comment: https://github.com/osmlab/to-fix/issues/207#issuecomment-299640587

**Comment by govvin** [comment]
>  No existing buildings in Bing/Mapbox

:eyes: hmm ... and yet, many of the change sets has imagery tagged as coming from Bing.

**Comment by govvin** [comment]
This could have been prevented using Terracing, in JOSM

![image](https://cloud.githubusercontent.com/assets/5821688/25995718/4958ace6-3746-11e7-877a-3d899ba36be6.png)
Ref: https://www.openstreetmap.org/changeset/19386393#map=18/14.42278/120.87864

**Comment by govvin** [comment]
Tagged as `building` instead of `landuse`, edits by same user.

![image](https://cloud.githubusercontent.com/assets/5821688/25995972/5c5dcc3a-3747-11e7-94bd-13385d348d61.png)

**Comment by govvin** [comment]
Tagging typo: `province` is not the same as "Province"

![image](https://cloud.githubusercontent.com/assets/5821688/25996079/f38b3142-3747-11e7-827a-a31fcf865c26.png)

**Comment by govvin** [comment]
Some buildings are left un-tagged.

![image](https://cloud.githubusercontent.com/assets/5821688/25996119/25126dde-3748-11e7-967b-5bfa0ce2077e.png)

**Comment by govvin** [comment]
Mappers mapping the same area, on the same date. Are they using two different TM tasks for the same area?
![image](https://cloud.githubusercontent.com/assets/5821688/26030320/b4c72dda-3882-11e7-9f60-3a5f5b487534.png)

**Comment by govvin** [comment]
But why...?!

![image](https://cloud.githubusercontent.com/assets/5821688/26031998/12ed1672-38ba-11e7-8dbb-a0e6d93ce999.png)

**Comment by govvin** [comment]
Lots of room for improving digitizing quality with more coaching/training.  Editor from George Washington University(?), from 4 years ago.

![image](https://cloud.githubusercontent.com/assets/5821688/26042467/58b0b96c-3968-11e7-9cf8-20048f3dbab6.png)

**Comment by govvin** [comment]
Observation: 
* Two different mappers added the building about a month apart, using the hashtag "#ProjectNOAH-ISIAH", then purportedly validated by another user about a month later. 
* All users were using JOSM, which by default would validate these updates for errors, but was ignored by the last two users.

![image](https://cloud.githubusercontent.com/assets/5821688/26086289/69772b3c-3a1c-11e7-8d64-b2d113642ed3.png)

**Comment by govvin** [comment]
Observation: Urgh!

![image](https://cloud.githubusercontent.com/assets/5821688/26233527/9e7c61dc-3c90-11e7-9e9b-4529c5716886.png)

https://www.openstreetmap.org/way/323377991

**Comment by govvin** [comment]
**Observation**: copy-paste? There's a terracing tool

![image](https://cloud.githubusercontent.com/assets/5821688/26233569/e6d125a8-3c90-11e7-877a-2f101278fca4.png)

**Comment by govvin** [comment]
Observation: Another one from the GWU group. Digitized by two different users, two minutes apart. It doesn't say whether the TM was used.

![image](https://cloud.githubusercontent.com/assets/5821688/26284597/f1a51dee-3e71-11e7-8ef0-d7769f367792.png)

**Comment by govvin** [comment]
**Observation** User duplicating buildings of the same shape and size. Got otiose and left unused extras scattered in the area.

![image](https://cloud.githubusercontent.com/assets/5821688/26534503/7115513a-4457-11e7-97d8-5d2a836a3e4c.png)
![image](https://cloud.githubusercontent.com/assets/5821688/26534539/e0aad290-4457-11e7-8b8f-d7572e4ae054.png)

**Comment by govvin** [comment]
In case you're utilizing the DigitalGlobe imagery, you might notice that the alignment doesn't always match. If you're also using JOSM, one other things we can do is to align DigitalGlobe with Bing, and store the offsets to the Imagery Offsets Database - this would allow us to have a (more or less) standard alignment settings for future use.

### What are the JOSM plugins needed:

#### [Utilsplugin](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/utilsplugin2#Use_custom_URL_.28Shift.2BH.29)
The plugin lets you open a custom URL in default browser (default shortcut: SHIFT+H) with data from selected node or location of center of the screen.  

In settings to preferences/utilsplugin2-tab or customurls.txt in JOSM folder, add an entry:

|Name | URL|
|- | -|
|`Nominatim` | `http://nominatim.openstreetmap.org/reverse?format=xml&lat={#lat}&lon={#lon}&zoom=13&addressdetails=0`|

#### [imagery_offset_db](https://wiki.openstreetmap.org/wiki/Imagery_Offset_Database)
Please read the [Imagery offset quickstart](https://wiki.openstreetmap.org/wiki/JOSM/Plugins/Imagery_Offset_Database/Quick_Start) on how to use, and align imagery using this tool.

## How to:
The browser will display local information about the area:
![image](https://cloud.githubusercontent.com/assets/5821688/26611762/e31b00cc-45e2-11e7-92b2-9dc2ca611622.png)

You may copy the display name `"Holy Spirit, Kapalaran Su…etro Manila, Philippines"` and use value when storing the offset to the database:
![image](https://cloud.githubusercontent.com/assets/5821688/26611787/2662b6b8-45e3-11e7-9981-daa0ac3d250e.png)

And you're done!

**Comment by govvin** [comment]
**Observations:** Polygons are over-sized compare to visual details available from imagery. Why?!

![image](https://cloud.githubusercontent.com/assets/5821688/26751610/09cedab0-4870-11e7-92ab-27c66682e7ce.png)

**Comment by govvin** [comment]
**Observations:** schadow1 call his changeset a "fix" attempt, but merely added address tags to orphan nodes made by the original mapper. 

Details: https://osmcha.mapbox.com/46293366. 

The validator could either have fixed the nodes by completing the digitizing, or just removed the nodes altogether.

![image](https://cloud.githubusercontent.com/assets/5821688/26753297/02e262b4-4896-11e7-9b2d-d33b36070ed2.png)

**Comment by vyruz32** [comment]
I don't know if I'm impressed or horrified but this is dedication right here. 

![image](https://user-images.githubusercontent.com/1816887/26862140-8413f482-4b7b-11e7-808f-f08a760a8ff1.png)

**Comment by govvin** [comment]
Are to-fix stats up-to-date? So far, only 23% complete?

**Comment by maning** [comment]
We have 17K overlapping buildings to date.  To-fix instance is now out of service. Closing this ticket.  Let's open a new one for separate tasking.  I suggest we use maproulette.
