### ISSUE TITLE
Barangay Halls incompletely tagged as office=government

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#15]
In recent edits in Batangas City, supposedly an LGU-led effort, I noticed they were tagging barangay halls as:
```
name=*
office=government
```

See [this](https://openstreetmap.org/changeset/48749193) comment I left in one of the change sets.

## To Do
- [ ] - [query](http://overpass-turbo.eu/s/ph0) for all features using Overpass Turbo and export to JOSM
- [ ] - review and fix incomplete tags. See Tags section below.
- [ ] - revise PH Mapping Conventions docs

### Basic
```
name=*
amenity=townhall
townhall:type=village
```

### Extended
In addition to the basic tags, the following are tags are recommended to be added
```
is_in:*=* (or addr:*=*)
contact:*=*
````
### Advanced
```
building=public
building:levels=*
office=government
government=administrative
admin_level=10
```
##### Example
```
name=Bacong Barangay Hall
amenity=townhall
townhall:type=village
is_in:hamlet=Lusbak
is_in:province=Bohol
is_in:town=Anda
is_in:village=Bacong
building=public
building:levels=2
office=government
government=administrative
admin_level=10
```

## Feature geometry
Use a closed way to digitize the building where possible. If not, use a node.

Are there objections to this?

**Comment by govvin** [comment]
Supposedly, there's an on-gong Batangas CPDO led effort to map using OSM:

So far, I found these JOSM users contributing in that AOI and may be part of that effort:

- Brad-M, https://api.openstreetmap.org/api/0.6/changesets?user=4813930
- EAA22, https://api.openstreetmap.org/api/0.6/changesets?user=5393360
- Leipo Spes, https://api.openstreetmap.org/api/0.6/changesets?user=5766675

I sent these users a private message to inquire about the particulars of their effort, and extended an offer to assist to address the issues related to their practice.

**Comment by govvin** [comment]
Illustrative fix: https://www.openstreetmap.org/changeset/48961780

**Comment by maning** [comment]
cc @TagaSanPedroAko

**Comment by govvin** [comment]
This issue is part of https://github.com/OSMPH/papercut_fix/issues/12

**Comment by govvin** [comment]
Fixed: https://www.openstreetmap.org/changeset/57594016
