### ISSUE TITLE
Macabebe and Masantol towns should be included in Pampanga borders and not Bulacan

### ISSUE THREAD

**Issue by JAT86** [OSMPH/papercut_fix#18]
Hello. I have noticed that for a long time, the borders of Pampanga province doesn't (fully) include the municipalities of Macabebe and Masantol situated to the southeast near Manila Bay. Here is the link to a note I added. The river appears to be the border between Pampanga and Bulacan. In fact, the Consuelo village nearby is tagged as located within Masantol:

![map](https://user-images.githubusercontent.com/30237173/28326043-2fef4232-6c12-11e7-8366-a244bb791c66.png)

https://www.openstreetmap.org/?mlat=14.8330&mlon=120.6797#map=12/14.8331/120.6797&layers=N

If you have time, could you please fix those borders? Thank you.

**Comment by govvin** [comment]
Thank you for your detailed comments. (We hope) someone can attend to this soon.

If you want to attempt a fix and only need instructions on how to do it yourself, just say so.

**Comment by govvin** [comment]
[Fixed](https://www.openstreetmap.org/changeset/78798851).
