### ISSUE TITLE
Kumalarang should be part of Zamboanga del Sur

### ISSUE THREAD

**Issue by JAT86** [OSMPH/papercut_fix#19]
The town of Kumalarang is currently covered by Zamboanga Sibugay's borders. Kindly fix Zamboanga del Sur's borders to include Kumalarang:

![kumalarangerror](https://user-images.githubusercontent.com/30237173/28404049-337e5c32-6d5a-11e7-9305-46df05dd4d0c.png)

http://www.openstreetmap.org/#map=12/7.7656/123.1643

Thanks.

**Comment by govvin** [comment]
Fixed in https://osm.org/changeset/78551436
