### ISSUE TITLE
OSM objects in PH attributed to Google

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#2]
According to this [query](http://overpass-turbo.eu/s/dpe), we have Philippine data in OSM that's attributed to Google. The Legal FAQ states that **[we cannot trace from these sources](http://wiki.openstreetmap.org/wiki/Legal_FAQ#2a._Can_I_trace_data_from_Google_Maps.2FNokia_Maps.2F....3F)**.

> Loaded – nodes: 3574, ways: 31, relations: 0

@maning proposed course of action: 
1. Review all of them, and leave comments on the changeset.
2. Advise mappers to rectify or delete said data. 
3. If no feedback is received, delete them after a week or revert to previous state, on 29th December.

For reference,  data from this query is available as a [gist](https://gist.github.com/anonymous/6f02d2a9acff9251402e).
##### To do:
- [x] contact authors, and inform them of the issue
- [x] wait for response
- [ ] revert change set
###### Edits:
- Original query, without meta is http://overpass-turbo.eu/s/dnl

**Comment by maning** [comment]
I commented on the following changesets:

* https://www.openstreetmap.org/changeset/17324810
* http://www.openstreetmap.org/changeset/18862003
* http://www.openstreetmap.org/changeset/18871471

**Comment by govvin** [comment]
Thank you @maning

**Comment by govvin** [comment]
Fixed by author: http://www.osm.org/changeset/36239641

**Comment by govvin** [comment]
This issue is close to three years old already. Affected change sets should be reverted, knowing the provenance of these particular datasets.

**Comment by govvin** [comment]
See: https://www.openstreetmap.org/changeset/57589711

All objects returned by the query was validated individually. Where an older version is available, the object was rolled back to said version (I.e. attributes added from an invalid source.)

Where the object is the initial version, the object is removed entirely.
