### ISSUE TITLE
Laak should be within Compostela Valley's borders

### ISSUE THREAD

**Issue by JAT86** [OSMPH/papercut_fix#20]
The town of Laak is erroneously located within Davao del Norte's borders, instead of Compostela Valley:

![laakerror](https://user-images.githubusercontent.com/30237173/28514432-85b65d76-708c-11e7-8a0f-c00ca1289e88.png)

http://www.openstreetmap.org/node/198492714#map=10/7.7294/125.9129

Kindly fix Compostela Valley's borders to include Laak.
Thanks.

**Comment by govvin** [comment]
[Fixed](https://www.openstreetmap.org/changeset/78796076). Laak now included in Davao de Oro (aka Compostela Valley)
