### ISSUE TITLE
Minor adjustments in Tarlac's borders to include Anao

### ISSUE THREAD

**Issue by JAT86** [OSMPH/papercut_fix#21]
Kindly fix Tarlac's borders to include the town of Anao (erroneously located within Nueva Ecija):

![anaoerror](https://user-images.githubusercontent.com/30237173/28514846-198516f4-708e-11e7-8eb8-51d5f449165c.png)

http://www.openstreetmap.org/node/198510040#map=13/15.7327/120.6517

Thanks.

**Comment by govvin** [comment]
Already fixed.
