### ISSUE TITLE
Bangon Marawi  Mapping Project

### ISSUE THREAD

**Issue by maning** [OSMPH/papercut_fix#27]
_Quick overview of the project.  Specific tasks will be prepared soon_

The armed conflict in Marawi City, Lanao Del Sur started on May 23, 2017 between terrorist groups and Government troops. After five months of fighting, the Government has officially announced today the end of all military operations.  This conflict has 359,000 people and has left the city heavily damaged and destroyed particularly inside the main battle area.  As OSM volunteers we have seen how our efforts have been useful and helpful during a crisis.  In the case of the case of the war Marawi, we could help out in digiziting satellite imagery and provide maps that will support Government, NGO’s, Aid organizations and other related groups in their work that is focused on the assistance of its residents and in the recovery, reconstruction and rehabilitation of Marawi City.
 
#### Community Action
 - **Proponent**: @banitopinoy 
- Coordination: https://github.com/OSMPH/papercut_fix/projects/1
- Public discussions: 
   - Mailing List - https://lists.openstreetmap.org/pipermail/talk-ph/2017-October/006170.html
   - Social Media - https://www.fb.com/groups/osmph/permalink/532661363737913/

------

## Objectives

- Map out road networks
- Map out damaged structures
- Map out houses and building footprints

## Resource needs
- [x] Pre-conflict Imagery
- [ ] Post-conflict aerial imagery
- [ ] Street-level imagery
- [ ] On-the-ground contacts

------
### See also
* https://en.wikipedia.org/wiki/Battle_of_Marawi

**Comment by seav** [comment]
Haven't looked into it so far but is there anything we can do prior to the updated imagery being available? Maybe we can look at unmapped roads and the like? Maybe we can share imagery alignment corrections for existing imagery?

**Comment by maning** [comment]
![screen shot 2017-10-24 at 07 16 54](https://user-images.githubusercontent.com/353700/31921149-5aed87d0-b88b-11e7-9fd3-c155699c8e4f.png)

Happening in OSM-PH FB.

**Comment by maning** [comment]
> Maybe we can look at unmapped roads and the like?

@seav Should we start creating a task for mapping with pre-conflict imagery?

**Comment by govvin** [comment]
@maning 
I agree with @seav . We can start with a TM to cover **just** road networks

**Comment by govvin** [comment]
This is a big task, and might be difficult to keep track with just a ticket. I made our first [project](https://github.com/OSMPH/papercut_fix/projects/1) to keep track of this

**Comment by maning** [comment]
> This is a big task, and might be difficult to keep track with just a ticket. I made our first project to keep track of this.

Agree, lets use this ticket as meta page for coordination.  Then move to specific tickets for mapping projects.

**Comment by maning** [comment]
Existing imagery review: https://github.com/OSMPH/papercut_fix/issues/28
In short DG standard wins for me.

**Comment by schadow1** [comment]
I have directly coordinated with the drone pilots involved in  drone mapping during the time of the conflict and was directed to gain permission from Western Mindanao Command. I was shown samples of the UAV imageries. They were taken around July at 120+MASL altitude. I have no direct contact to WESTMINCOM thus coursing through Joint Task Force Tawi-Tawi where I have gained contact through my mapping expedition in the area when the siege broke out in Lanao. Currently in process of coordination.

**Comment by schadow1** [comment]
Request letter has been sent to Maj. Gen. Carlito Galvez Jr of Western Mindanao Command to request access to UAV imagery of Marawi City.

**Comment by banitopinoy** [comment]
@schadow1 , This is good news.  We hope to have a positive response concerning our request.

**Comment by govvin** [comment]
@schadow1 Just make sure you clarify the permission we're after should be ODbL-compatible.

**Comment by schadow1** [comment]
The request to WESTMINCOM for UAV imagery  has been forwarded to Major Eugene Ramon as of 2017 - 11-02

**Comment by schadow1** [comment]
As per Major Ramon, he is working with the hq in Pagadian City as the files will be dispatched from there.

**Comment by banitopinoy** [comment]
@schadow1 , will wait for the development of the availability of the UAV imagery and let us hope that we get hold of the images so that we could start the mapping.

**Comment by maning** [comment]
> availability of the UAV imagery

@schadow1 any movement here?

**Comment by schadow1** [comment]
UAV: Under approval of Col. Luzon in Pagadian. But not yet signed as he is in a mission. I was pre-informed, there will be requirements. I will relay this as soon as info is available.

**Comment by govvin** [comment]
IttC/MapGive is requesting for information about partnerships and/or end-users of the data. Have we established any collaborative relationships with local government, Humanitarian, or community groups in Marawi? @banitopinoy

￼

**Comment by banitopinoy** [comment]
Happy to know that MapGive is keen for partnership. If they do have resources in accessing post war images, that will be really useful. @govvin  are you in touch with IttC? 

Right now, we have not communicated formally to any NGO, humanitarian or local groups in Marawi for this project.  The only formal communication we have sent is to the AFP which Ervin crafted.

**Comment by govvin** [comment]
@banitopinoy , Bunny I'm sorry for not explaining myself clearly. That wasn't MapGive seeking for partners. The Imagery to the Crowd (IttC) initiative of the Humanitarian Information Unit of the U.S. State Department process imagery requests for the MapGive project.

Their evaluation includes determining how the data affects Humanitarian work in the area of interest, including existing partnerships that stand to benefit from them. If partnerships are already established, the imagery request has a better chance of getting approved.

**Comment by schadow1** [comment]
I got a response today November 17, from the acting chief of intelligence of AFP. He will get back to me once he and his team has declassified the imagery due to on-going operations. No timeframe given.
Although he also segued that if we wish to do our flybys ourselves, they are willing to provide security clearance.

**Comment by maning** [comment]
No movement here. Closing.

**Comment by schadow1** [comment]
Upon our last email conversation on the matter last 11/30/2017, it was decided upon that the imagery will not be used for tracing in OSM as according to the discussion, "any derived data is incompatible with OSM".
With consent from the data owners, derived structure status data however was already made available outside of OSM under ODbL since December 2017 due to the urgency of the matter. And is given directly to the Defense Secretary as per the President who received the data in the same month.
