### ISSUE TITLE
Imagery review for Marawi (pre-conflict)

### ISSUE THREAD

**Issue by maning** [OSMPH/papercut_fix#28]
I did a quick :eyeglasses: ball of all existing pre-conflict :artificial_satellite: imagery available.  DG Standard wins. Although there are clouldy areas south of main city, this can be complemented by using DG Premium or ESRI.  Alignment for all images is slightly different but ~<5 meters.

**For all pre-conflict mapping I propose we use DG Standard.**  Another pass of review welcome!

|Provider|Quality|Recency|Alignment|Notes
|----|----|----|----|----|
|Bing ![screen shot 2017-10-24 at 21 21 37](https://user-images.githubusercontent.com/353700/31954258-c02e2ce0-b902-11e7-8343-85b125ca620e.png)|:star2: :star2:  | (ca 2012) |:star2: | Current data aligned to this source.|
|DG Premium ![screen shot 2017-10-24 at 21 21 53](https://user-images.githubusercontent.com/353700/31954257-bffe4bc4-b902-11e7-85d2-a8f62cf63444.png)|:star2:  | :star2: (beyond 2012)| :star2:| Same image capture as ESRI |
|DG Standard ![screen shot 2017-10-24 at 21 22 12](https://user-images.githubusercontent.com/353700/31954255-bfc97afc-b902-11e7-8e45-1445f208df14.png)|:star2: :star2:  | :star2: (beyond 2012) | :star2:| 4 :star2: but has cloudy section south of downtown|
|ESRI World Imagery ![screen shot 2017-10-24 at 21 22 28](https://user-images.githubusercontent.com/353700/31954254-bf996c4a-b902-11e7-963e-74f4fa6f0f6e.png)|:star2:  | :star2: (beyond 2012)| :star2:| Same image capture as DG premium|
|Mapbox ![screen shot 2017-10-24 at 21 22 44](https://user-images.githubusercontent.com/353700/31954253-bf666c3c-b902-11e7-967e-486618d406f8.png)| - | - | - | Failed the eval, but working on updating the imagery|

# See also

Location: https://www.openstreetmap.org/edit?editor=id#map=15/7.9965/124.2958

Alignment from existing GPX

![marawi_gpx](https://user-images.githubusercontent.com/353700/31954392-13a9f16a-b903-11e7-9330-3bb191d56cdb.gif)

Recency based on building changes

![marawi](https://user-images.githubusercontent.com/353700/31954393-13e03cde-b903-11e7-9bc8-6179084b8415.gif)

**Comment by govvin** [comment]
Within the AOI, the digitized road coverage already looks very good, and we could use pre-conflict imagery for validation. Bing could be good enough.

Need to clarify if we want to map just the AOI, or the whole of Marawi.

**Comment by maning** [comment]
Imagery update from Mapbox, next actions: update OP for Mapbox 🌟 rating.
![screen shot 2017-11-08 at 09 29 16](https://user-images.githubusercontent.com/353700/32530987-7818e4e8-c467-11e7-8cc5-4ca940a530d5.png)

**Comment by banitopinoy** [comment]
Letter of request for the drone images have been submitted to AFP in Camp Aguinaldo.  Hoping for a favorable response.

**Comment by schadow1** [comment]
Made offsets available for Bing, DG Standard and DG Premium verified from the acquired imagery that is in EPSG 3857 projection. Once we get a go, I'll be publishing the WMS for the tiles.
![marawi-offset](https://user-images.githubusercontent.com/6179495/33589953-fee361ba-d9b6-11e7-8d1e-2190459a6bff.jpg)
