### ISSUE TITLE
revert and cleanup "John Castillo Soberano" edits

### ISSUE THREAD

**Issue by ianlopez1115** [OSMPH/papercut_fix#29]
A user named "[John Castillo Soberano](http://whosthat.osmz.ru/?id=4216924)", presumably the same user as "[Panko kale Ty](http://whosthat.osmz.ru/?id=4203872)" added false information on the map connected to radio stations (see a list of changesets [OSM history]( http://www.openstreetmap.org/user/John%20Castillo%20Soberano/history), [OSMCha](https://osmcha.mapbox.com/changesets/53195232?filters=%7B%22date__gte%22%3A%5B%7B%22label%22%3A%22%22%2C%22value%22%3Anull%7D%5D%2C%22users%22%3A%5B%7B%22label%22%3A%22John%20Castillo%20Soberano%22%2C%22value%22%3A%22John%20Castillo%20Soberano%22%7D%5D%7D)). Similar to the Panko Kale Ty account, it is suspected of being a permanently banned Wikipedia user [based on editing patterns](https://en.wikipedia.org/wiki/Wikipedia:Long-term_abuse/Bertrand101#Basic_information), who is known for using [sockpuppet](https://en.wikipedia.org/wiki/Wikipedia:Sockpuppet_investigations/Bertrand101) [accounts](https://en.wikipedia.org/wiki/Wikipedia:Sockpuppet_investigations/Bertrand101/Archive) to evade bans and blocks.

TODO:
- [ ] Delete and rollback edits (modify edits to reflect accurate information, if necessary)
- [x] Close notes made and/or commented by the user

Areas that the user edited
- Metro Manila
- Bulacan Province
- Nueva Ecija
- Nueva Vizcaya
- Santiago, Isabela

**Comment by ianlopez1115** [comment]
Valenzuela area now cleared (http://www.openstreetmap.org/changeset/53332316)

**Comment by ianlopez1115** [comment]
San Jose, Nueva Ecija (http://www.openstreetmap.org/changeset/53332446) and Ugong Norte, Quezon City (http://www.openstreetmap.org/changeset/53332665) now cleared. Keeping this open for a week.

**Comment by TagaSanPedroAko** [comment]
I reverted edits I spotted Guadalupe Viejo, Makati (http://www.openstreetmap.org/changeset/53682665). User remains active for this week, continuing to add other fake radio stations around. Please keep this open until the user stops, or someone requests it to be blocked.

**Comment by TagaSanPedroAko** [comment]
Seen this user again, and reverted his edits on the spot. See these:
*http://www.openstreetmap.org/changeset/54050633 (in Ortigas Complex)
*http://www.openstreetmap.org/changeset/54050819#map=19/14.73400/120.92644 (in Wawang Pulo, Valenzuela, near boundary with Obando, Bulacan) 

Other locations may be okay, but outright fake radio stations, especially those that are "proposed" , may be deleted once spotted.

**Comment by ianlopez1115** [comment]
Minor cleanups undertaken tonight, issue closed for now (until account resurfaces)

**Comment by ianlopez1115** [comment]
Related: "[DZCA Aking Radyo 1170 Khz](http://whosthat.osmz.ru/?id=8694013)", presumably the same user as "Panko kale Ty" and "John Castillo Soberano" added false information on the map connected to radio stations in Ilocos Norte, Isabela and Bulacan (see [OSM history]( https://www.openstreetmap.org/user/DZCA%20Aking%20Radyo%201170%20Khz/history) and [OSMCha (login required)](https://osmcha.org/?filters={"date__gte"%3A[{"label"%3A"2018-08-12"%2C"value"%3A"2018-08-12"}]%2C"date__lte"%3A[{"label"%3A"2018-08-19"%2C"value"%3A"2018-08-19"}]%2C"users"%3A[{"label"%3A"DZCA%20Aking%20Radyo%201170%20Khz"%2C"value"%3A"DZCA%20Aking%20Radyo%201170%20Khz"}]})). Said user's edits have been reverted in [changeset 82712115](https://www.openstreetmap.org/changeset/82712115).

**Comment by ianlopez1115** [comment]
Most recent edits from this user now mopped up ([changeset 82823237](https://www.openstreetmap.org/changeset/82823237) for Obando, Bulacan, [changeset 82828505](https://www.openstreetmap.org/changeset/82828505) for Iloilo City) - take note that his last edits were logged almost 2 years ago

**Comment by TagaSanPedroAko** [comment]
@ianlopez1115 @govvin User’s also spotted in GMaps, and is all behind the “Audiovisual Communications Inc.” trash there. I just deleted of some of their garbage around Alaminos City and Nueva Vizcaya.

**Comment by ianlopez1115** [comment]
It appears that Panko Kale Ty/John Castillo Soberano or a sockpuppet using the account "[SBIDWHG](http://whosthat.osmz.ru/?id=17304278)" created nonexisting radio station-related facilities in La Union yesterday (see [OSM history](https://www.openstreetmap.org/user/SBIDWHG/history) and [OSMCha (login required)](https://osmcha.org/filters?filters=%7B%22uids%22%3A%5B%7B%22label%22%3A%2217304278%22%2C%22value%22%3A%2217304278%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%7D). Said user's edits have been reverted in changesets [127000588](https://www.openstreetmap.org/changeset/127000588) and [127000621](https://www.openstreetmap.org/changeset/127000621).

**Comment by ianlopez1115** [comment]
Same user behind Panko Kale Ty/John Castillo Soberano recently created the "[ACIPasig](http://whosthat.osmz.ru/?id=18495827)" account (name appears to allude to (1) [Audiovisual Communications Incorporated](https://rx931.com/About), a company operating radio stations in key parts of the country which has been a frequent subject of hoaxes made by the user in question among others and (2) Pasig City, the location of its main office) which added a duplicate radio tower approximately 30-40 meters northeast of an existing yet inactive AM radio transmitter near the Tapayan Pumping Station in Barangay San Juan, Taytay (see [OSM history](https://www.openstreetmap.org/user/ACIPasig/history) and [OSMCha (login required)](https://osmcha.org/filters?filters=%7B%22uids%22%3A%5B%7B%22label%22%3A%2218495827%22%2C%22value%22%3A%2218495827%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%7D). Said edit was reverted in changeset [132618638](https://www.openstreetmap.org/changeset/132618638).

**Comment by ianlopez1115** [comment]
Another copycat/sockpuppet appeared with the username [DWNR](http://whosthat.osmz.ru/?id=18498306) which made edits in San Juan, Taytay, Rizal (reverted in changeset [132631035](https://www.openstreetmap.org/changeset/132631035)), Obando, Bulacan (reverted in changeset [132631911](https://www.openstreetmap.org/changeset/132631911)), Legazpi, Albay (reverted in [132631296](https://www.openstreetmap.org/changeset/132631296)), Cebu City (reverted in [132631856](https://www.openstreetmap.org/changeset/132631856)), and Davao City (reverted in [132631599](https://www.openstreetmap.org/changeset/132631599)).

**Comment by govvin** [comment]
This new [account ](https://www.openstreetmap.org/user/NickPalparan) started adding transmitters from the get-go. 

Might be another clone account.

**Comment by ianlopez1115** [comment]
Another challenger appeared a few hours ago using the moniker DWNRNewsRadio ([OSM Profile](https://www.openstreetmap.org/user/DWNRNewsRadio), [Find Suspicious Changesets](https://resultmaps.neis-one.org/osm-suspicious?uid=18616909), [Who's That?](http://whosthat.osmz.ru/?id=18616909)).

As of today, the ACIPasig account is still active. I managed to delete some of the user's edits close to the inactive AM radio transmitter near the Tapayan Pumping Station in Barangay San Juan, Taytay in changeset [133313085](https://www.openstreetmap.org/changeset/133313085). Will dedicate some of my time today to revert and/or delete such changes.

**Comment by ianlopez1115** [comment]
Apparently the ACINewsRadio1170am account ([OSM Profile](https://www.openstreetmap.org/user/ACINewsRadio1170am), [Find Suspicious Changesets](https://resultmaps.neis-one.org/osm-suspicious?uid=18546105), [Who's That?](http://whosthat.osmz.ru/?id=18546105)) went undetected until a few hours - this is being rectified in today's wave of deletions and reversions.

**Comment by ianlopez1115** [comment]
Another player has entered the game - rather another sockpuppet or meatpuppet was spotted (h/t @DP24PH via Telegram) with the moniker JOJIDAVID ([OSM Profile](https://www.openstreetmap.org/user/JOJIDAVID), [Who's That?](http://whosthat.osmz.ru/?id=18710998)) who recently added fake radio transmitter sites in Obando, Valenzuela, Tarlac province and Baguio City. Such changes along with edits made by similar sockpuppets and meatpuppets on the map will be dealt with in the coming days and weeks.

Also, the ACIPasigCity account ([OSM Profile](https://www.openstreetmap.org/user/ACIPasigCity), [Who's That?](http://whosthat.osmz.ru/?id=18629580)), which as an editing style similar to the ACIPasig account, was recently discovered and its edits have been removed or are being removed.

**Comment by ianlopez1115** [comment]
Another new account with the username CiscoJayFlores ([OSM Profile](https://www.openstreetmap.org/user/CiscoJayFlores), [Who's That?](http://whosthat.osmz.ru/?id=18816131)) recently added one fake radio transmitter site in Dagupan City and copied map data from Google Maps, particularly a nearby street name and address info (see attachments), such edits were reverted in changeset [134299480](https://www.openstreetmap.org/changeset/134299480).

![Screenshot from Google Maps](https://user-images.githubusercontent.com/1140532/228824702-c6b03582-66af-4ff3-8381-639a756b2625.png)
![Screenshot from OpenStreetMap showing the affected area](https://user-images.githubusercontent.com/1140532/228824745-91a70b11-4fc6-42b4-8ac9-9c39a1fd1bc2.png)

**Comment by ianlopez1115** [comment]
"Radyo Komentaryo" ([OSM Profile](https://www.openstreetmap.org/user/Radyo%20Komentaryo), [Who's That?](http://whosthat.osmz.ru/?id=18825604)), an account created ~48 hours ago, added a duplicate feature at the site of the inactive AM radio transmitter near the Tapayan Pumping Station in Barangay San Juan, Taytay and a added fake radio transmitter along Bulak Road in Meycauayan, Bulacan (both features were removed in changeset [134420523](https://www.openstreetmap.org/changeset/134420523)).

**Comment by govvin** [comment]
@ianlopez1115 , if these are only *inactive* transmitters, and the physical facilities are still present, perhaps they could be retained with appropriate [lifecycle](https://wiki.openstreetmap.org/wiki/Lifecycle_prefix) tags?

> "Radyo Komentaryo" ([OSM Profile](https://www.openstreetmap.org/user/Radyo%20Komentaryo), [Who's That?](http://whosthat.osmz.ru/?id=18825604)), an account created ~48 hours ago, added a duplicate feature at the site of the inactive AM radio transmitter near the Tapayan Pumping Station in Barangay San Juan, Taytay and a added fake radio transmitter along Bulak Road in Meycauayan, Bulacan (both features were removed in changeset [134420523](https://www.openstreetmap.org/changeset/134420523)).
