### ISSUE TITLE
Edits by "MembersOnly"

### ISSUE THREAD

**Issue by TagaSanPedroAko** [OSMPH/papercut_fix#30]
This user, "MembersOnly", are seen making fantasy edits in the pattern of "bryanpiczon", and is again causing troublesome edits. Some fake edits by "MembersOnly" I reverted include an addition of a fake island near Catbalogan, and adding a fake connection of HVDC Leyte-Luzon to a 69,000 volt line and Bac-Man Geothermal Power Plant. Please keep a monitor of that user, and revert any edit that we must believe to be fake.

**Comment by govvin** [comment]
Possibly related to "Bryan Piczon", see https://github.com/OSMPH/papercut_fix/issues/30

**Comment by TagaSanPedroAko** [comment]
User is last sighted adding adding fake features in the US, such as in New Jersey. Maybe we may revert them or ask the OSM-US community there to revert them.

**Comment by govvin** [comment]
That's unfortunate @TagaSanPedroAko  :( 

Please record your attempts to reach touch with the user, or take note of the change set comments you left to that effect.  This should be helpful when you elevate your concern to DWG.

You may use this ticket for that purpose.

**Comment by TagaSanPedroAko** [comment]
I just sent an email to DWG, with a link to this ticket and details about the latest vandalism.

I have contacted the user previously, but only sending another email that says nothing. I have left comments on the latest edits that involved the latest vandalism incidents, especially the Batangas City vandalism incidents (i.e. vandalism on Sta. Clara Elementary School, and adding of a non-existent "Kanu Bay" near Batangas Port).
