### ISSUE TITLE
Organized mapping from UP Los Baños, using invalid tags?

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#33]
Has anyone noticed recent edits in Los Baños with the following (incomplete) tags:
* `repair=*`
* `material=*`
* `level=*`

![image](https://user-images.githubusercontent.com/5821688/32696517-371fa886-c7b5-11e7-9473-43069cf3963f.png)

There appears to be an organized mapping effort out of UPLB? Check it out on [OSMCha](https://osmcha.mapbox.com/changesets/53633829?filters=%7B%22in_bbox%22%3A%5B%7B%22label%22%3A%22120.4792%2C13.2358%2C122.1059%2C14.8140%22%2C%22value%22%3A%22120.4792%2C13.2358%2C122.1059%2C14.8140%22%7D%5D%2C%22checked%22%3A%5B%7B%22value%22%3A%22False%22%2C%22label%22%3A%22False%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22value%22%3A%22%22%2C%22label%22%3A%22%22%7D%5D%2C%22users%22%3A%5B%7B%22label%22%3A%22sheinna%22%2C%22value%22%3A%22sheinna%22%7D%2C%7B%22label%22%3A%22Randell1011%22%2C%22value%22%3A%22Randell1011%22%7D%2C%7B%22label%22%3A%22Joven%20Pacyaya%22%2C%22value%22%3A%22Joven%20Pacyaya%22%7D%2C%7B%22label%22%3A%22hpalbuero%22%2C%22value%22%3A%22hpalbuero%22%7D%5D%7D).

**Comment by maning** [comment]
Commented on few [here](https://osmcha.mapbox.com/?filters=%7B%22in_bbox%22%3A%5B%7B%22label%22%3A%22120.4792%2C13.2358%2C122.1059%2C14.8140%22%2C%22value%22%3A%22120.4792%2C13.2358%2C122.1059%2C14.8140%22%7D%5D%2C%22checked%22%3A%5B%7B%22value%22%3A%22False%22%2C%22label%22%3A%22False%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22value%22%3A%22%22%2C%22label%22%3A%22%22%7D%5D%2C%22users%22%3A%5B%7B%22label%22%3A%22sheinna%22%2C%22value%22%3A%22sheinna%22%7D%2C%7B%22label%22%3A%22Randell1011%22%2C%22value%22%3A%22Randell1011%22%7D%2C%7B%22label%22%3A%22Joven%20Pacyaya%22%2C%22value%22%3A%22Joven%20Pacyaya%22%7D%2C%7B%22label%22%3A%22hpalbuero%22%2C%22value%22%3A%22hpalbuero%22%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22https%3A%2F%2Fgithub.com%2FOSMPH%2Fpapercut_fix%2Fissues%2F33%22%2C%22value%22%3A%22https%3A%2F%2Fgithub.com%2FOSMPH%2Fpapercut_fix%2Fissues%2F33%22%7D%5D%7D)

**Comment by govvin** [comment]
Fixed in #35 . Ian is in touch with the group.

**Comment by govvin** [comment]
No more activity.
