### ISSUE TITLE
Clean-up task in the Visayas region

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#34]
ThreeSixty Pharmacy is a popular drugstore/convenience store hybrid chain in the Visayas region. They are often erroneously tagged as "360 Pharmacy."

Overpass Turbo [query](http://overpass-turbo.eu/s/t3t) to retrieve the data.

Here's how a typical outlet looks like:
![image](https://user-images.githubusercontent.com/5821688/32946188-831d22c0-cbd1-11e7-8b6f-762b591c3a59.png)

OSM changeset hashtag: `https://git.io/vFyp0`

**Comment by maning** [comment]
Thanks @govvin https://www.openstreetmap.org/changeset/53872392

**Comment by govvin** [comment]
Might be a good idea to revisit this task from time-to-time.
