### ISSUE TITLE
For revert or redaction: Los Baños edits, using StreetView

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#35]
This was first reported in #33 , but now I have details from sheinna, one of the mappers:
![image](https://user-images.githubusercontent.com/5821688/32986697-8b853b04-cd12-11e7-873e-13ec264c5db7.png)

and my response:
![image](https://user-images.githubusercontent.com/5821688/32986745-1d197ce2-cd13-11e7-9a8f-8f939628156d.png)

Unfortunately, we may have to revert or redact the data

**Comment by ianlopez1115** [comment]
As someone who's in the area for over seven years, I can help out with the remapping efforts.

**Comment by govvin** [comment]
That's great, @ianlopez1115 ! Would you mind if I send them a message to tell them about your offer to help? Or, you could do that yourself. :smile_cat: 

Keep us posted.

I'm not reverting any data yet, they seem to be using the StreetView data for collecting attributes, but they available imagery for digitizing buildings.

**Comment by govvin** [comment]
The user confirmed the use of extracted data from StreetView:

![image](https://user-images.githubusercontent.com/5821688/33104019-e16d231a-cf60-11e7-9633-5fb75397c6e8.png)

The building tags will be redacted sometime this week, schedule permitting  - unless someone would like to assign themselves to doing it.

**Comment by govvin** [comment]
The affected data retrieved via this Overpass Turbo [query](http://overpass-turbo.eu/s/t8A), using their uids,  has been redacted of `building:*=*` tags, and replaced with generic `building=yes`, including fixing validation errors.

Noted: one of their teammates has deleted their user account.

@ianlopez1115 , one thing that's noticeable about their edits is the quality of their geometry, mapping overlapping buildings, and the use of `addr:housenumber=9999` . Perhaps, these are concerns you can discuss with them?

![image](https://user-images.githubusercontent.com/5821688/33112491-8348ee94-cf8e-11e7-8537-848534fc36c8.png)

![image](https://user-images.githubusercontent.com/5821688/33112576-ec4ce850-cf8e-11e7-99ba-405588e73b60.png)
