### ISSUE TITLE
Marawi Post-war imagery

### ISSUE THREAD

**Issue by schadow1** [OSMPH/papercut_fix#36]
Post-war imagery on the main battle area has been made available through WESTMINCOM as requested by @schadow1 . However publishing requires declassification from the Intelligence Services, Armed Forces of the Philippines (ISAFP). Schadow1 Expeditions already possesses the imagery dated 2017-11-09 for building status classification purposes only. However publishing to the web as imagery for high resolution public/limited view tracing has been halted prior clearance from ISAFP. 
![marawi-openlayer](https://user-images.githubusercontent.com/6179495/33591415-6a8247de-d9c0-11e7-9e65-5f434ad96f37.jpg)

Building classification has been initiated through Schadow1 Expeditions and is available for download in ODbL.
[Aftermath of the Battle of Marawi](http://www.s1expeditions.com/2017/11/223-marawi-battle-structures.html)

- [x] Post-war imagery request
- [x] Post-war imagery use for identification of structure status
- [ ] Post-war imagery declassification
- [ ] Post-war imagery for public/limited OSM tracing

**Comment by govvin** [comment]
Duplicate https://github.com/OSMPH/papercut_fix/issues/36. Continue in original issue.
