### ISSUE TITLE
Update Bottled/Mineral/Purfied Water shops

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#37]
Most of these Bottled/Mineral/Purified Water shops are currently tagged incorrectly as `amenity=drinking_water` or `shop=beverages`. These objects will be retrieved via Overpass Turbo, and reviewed individually, and replaced with [`shop=water`](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dwater),  as appropriate.

The appropriate [entry](https://wiki.openstreetmap.org/wiki/Philippines/Mapping_conventions#Convenience_Stores.2C_Food_Marts_.26_Supplies) in the local convention page has been updated.

**Comment by seav** [comment]
I have no objection to this proposal. 👍

**Comment by govvin** [comment]
Fixed! See [changeset](https://www.openstreetmap.org/changeset/56231414#map=6/13.936/122.175): 

Objects which don't have information (e.g. from their name) that didn't identify them as such a shop were left as-is.

Other objects retrieved from this query we're re-tagged as appropriate, based on available information. The more common ones were:
- `man_made=water_tap`
- `man_made=water_well`
- `natural=spring`
- `emergency=fire_hydrant`
- `office=company`
- `government=public_utility`

You may reuse this Overpass Turbo [query](http://overpass-turbo.eu/s/w1X), as part of future [maintenance tasks](https://github.com/OSMPH/papercut_fix/labels/laba-kusot-banlaw-kula) for PH data.

**Comment by schadow1** [comment]
Made changes to some of its remnants.
shop=purified_water to shop=water
https://www.openstreetmap.org/changeset/56231642

Ervin M.
*Schadow1 Expeditions* - A Filipino must not be a stranger to his own
motherland.
http://www.s1expeditions.com

**Comment by govvin** [comment]
Filled a ticket in carto, so this could be rendered on the map by default.
https://github.com/gravitystorm/openstreetmap-carto/issues/3060
