### ISSUE TITLE
highway=motorway_junction

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#4]
According to this [Overpass Turbo query](http://overpass-turbo.eu/s/dri), there are over 100 nodes in the country that uses this tag to indicate a crossing or road junction to orient people about turn offs for navigation.

These nodes are currently placed along or near these intersections, but are not on the actual node that connects the ways. 

Reviewing the [wiki](https://wiki.openstreetmap.org/wiki/Tag:junction%3Dyes), I found that a more appropriate tag is available: **[`junction=yes`](https://wiki.openstreetmap.org/wiki/Tag:junction%3Dyes).**

I've contacted the user who made these edits, and requested he consider editing and updating these tags. 

## To Do
- [x] contact editor, and wait for response
- [x] original author acknowledged message 
- [x] update and correct the tags.

**Comment by govvin** [comment]
Completed, 2016-003. Had a private conversation with the author of the majority of the datasets and xe agreed to use new tags in future edits.

**Comment by maning** [comment]
:rocket:
