### ISSUE TITLE
Using "ditch" for irrigation canals

### ISSUE THREAD

**Issue by JAT86** [OSMPH/papercut_fix#40]
Many farm "irrigation canals" are currently tagged as [canal]. "Canal" in its strict definition should be wide enough to be passable by ships. Some are tagged as [drain], which is too vague since all waterways drain water. We should most likely use [ditch] for such irrigation canals, whether cemented or not.

**Comment by govvin** [comment]
You're absolutely right @JAT86. I personally map these as ditches, but the common mis-tagging has more to do with the lingua franca , than an intention to mis-represent them as something else. Not are they the community accepted convention.

This should be an easy, but tedious task that can be done in a few hours with some help from volunteers.

Here's a quick and dirty query for Minndanao: https://overpass-turbo.eu/s/wPV

**Comment by govvin** [comment]
@JAT86 , for the convenience of all contributors interested to help out,  I've made a task available for all waterways currently tagged as "canal": https://tasks.hotosm.org/project/4279.

I hope this helps.

**Comment by govvin** [comment]
Stale request, inactive task.
