### ISSUE TITLE
Suspicious PoGo features, mapping for the renderer

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#46]
As expected with the release of a new version of the game, there are a flurry of new "parks" being added around. Here are some Overpass Turbo queries to try

-  [new parks in the last three days](http://overpass-turbo.eu/s/yxz)
-  [new parks since 23rd April.](http://overpass-turbo.eu/s/yrV)

I've gotten into an unproductive edit skirmish, so I'm withholding edits for now, but so far has found these "parks":
![image](https://user-images.githubusercontent.com/5821688/39459311-29838ca8-4d2d-11e8-906f-296a255046c2.png)

Some suspicious change sets that needs to be reviewed

- [x] https://www.openstreetmap.org/way/584572510 - fictitious edit
- [x] https://www.openstreetmap.org/way/583891664 - a square
- [x] http://www.openstreetmap.org/way/583739329 - seems to be grassy area
- [x] http://www.openstreetmap.org/way/584342472 - this seems to be a cemetery
- [x] http://www.openstreetmap.org/way/584343030 - this seems to be a cemetery
- [x] http://www.openstreetmap.org/way/584342612
- [x] https://www.openstreetmap.org/way/584555979 - suspicious edit

**Comment by govvin** [comment]
Do welcome mappers, and direct them to: [Tips for new Pokemon Go mappers](https://wiki.openstreetmap.org/wiki/Tips_for_new_(Pokemon_Go)_mappers)

**Comment by ianlopez1115** [comment]
Also found [this user](https://www.openstreetmap.org/user/trainerdrei/history), who tagged two areas in San Pablo City as "parks". I more or less fixed them [here](https://www.openstreetmap.org/changeset/64824124) and [here](https://www.openstreetmap.org/changeset/64824506).

**Comment by govvin** [comment]
Revisit this task in the future for periodic reviews.
