### ISSUE TITLE
Personal names in buildings - Lupang Arenda, Taytay, Rizal.

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#49]
Issue [raised](https://t.me/OSMph/2335) by Maning in Telegram.

I left a few changeset comments, but I'm fixing this now without waiting for a response from the editor. 

For reference, the OSM policy regarding private information: [Limitations on mapping private information](https://wiki.openstreetmap.org/wiki/Limitations_on_mapping_private_information)

Major concerns about these edits:
* publishing personal and private information in features
* geometry quality
* no project documentation, as required by OSMF policy

Other concerns:
* unconventional use of tags.
* Named features are capitalized

## Overpass Turbo query
Overpass Turbo [query for edits in the last 7 days](http://overpass-turbo.eu/s/HtV) in this particular area.

## OsmCha filter
* [All edits](https://osmcha.mapbox.com/filters?aoi=71a117d7-3d9d-4981-8660-cd763d36e553)
* [(known) Suspicious accounts](https://osmcha.mapbox.com/?aoi=43b75838-d983-4136-aa25-476691f10939)

## Who Did It
* All edits in [Lupang Arenda](https://simon04.dev.openstreetmap.org/whodidit/?zoom=16&lat=14.53784&lon=121.1075&layers=BTT)

**Comment by govvin** [comment]
Fixed. 304 names removed in changeset [65670622](https://www.openstreetmap.org/changeset/65670622)

**Comment by govvin** [comment]
Another mapper, freebeer, left a [comment](https://www.openstreetmap.org/changeset/65178844) on a changeset, and said that it should be reported to DWG for full redaction from the database. 

Email sent to DWG, 23rd December.

**Comment by govvin** [comment]
Editing activities resumed today, and no feedback was received from comments left on their changesets or the direct messages sent to them.

I've removed the names found, but retained other attributes they've added in this changeset
* [66019947](https://www.openstreetmap.org/changeset/66019947)

Will request DWG for a temporary block, to get the editors' attention.

**Comment by govvin** [comment]
@maning posted this issue in talk-ph: https://lists.openstreetmap.org/pipermail/talk-ph/2019-January/006348.html

**Comment by maning** [comment]
A new user with a similar editing pattern.  I reverted the 2 chnagesets created so far.

* https://www.openstreetmap.org/user/Edmichael/history#map=17/14.53798/121.10783

**Comment by govvin** [comment]
> A new user with a similar editing pattern. I reverted the 2 chnagesets created so far.
> 
>     * https://www.openstreetmap.org/user/Edmichael/history#map=17/14.53798/121.10783

Good catch, Maning

**Comment by govvin** [comment]
Note.

After 4 weeks from our first attempt to get in touch, somebody from the group of accounts editing in the area responds to a direct message we sent them. Will update for details, as soon as we have any to share.

**Comment by govvin** [comment]
Response from user Marianne received last Friday, 22nd March.

New editing activities noticed 23rd March,  by user [christianpaul](https://www.openstreetmap.org/user/cristianpaul)

**Comment by govvin** [comment]
The user Marianne has been in touch over the weekend, and has explained that the mapping effort is being conducted by the barangay (village) registry department, to record information related to their issuance of  "certificate of lot occupancy", and also to create public DRR maps, to inform the community about their local hazards and vulnerability.

They agreed to hold an online meeting to discuss the privacy-related issues they've had earlier, and is willing to work with the OSM community to ensure that they can comply with community guidelines.

**Comment by govvin** [comment]
Official contact has been made with the person responsible for initiating the mapping effort,  Ms. Marianne Mores of Barangay Santa Ana, Taytay, Rizal.

They agreed to have an online meeting on 27th March to discuss the issues identified by the community, and suggestions were offered to enable them to pursue the project without violating community guidelines on data privacy rights of the individuals, and other suggestions to improve the quality of the data they're adding, which they agreed to implement ASAP.

Among other things, they disclosed that this effort is related to their barangay's registry for issuing "Certificates of Land Occupancy", but the data will also be used to create community hazards and vulnerability maps in the future.

We encouraged them to publish additional information about their project, as expected for organized editing activities under OSMF guidelines: [Lupang Arenda Community Mapping wiki page](https://wiki.openstreetmap.org/wiki/Organised_Editing/Activities/Lupang_Arenda_Community_Mapping).

**Comment by govvin** [comment]
We have been in close contact with the barangay staff in charge of the community mapping effort, and they are planning to meet with some advocates in June, to:
* discuss their mapping plans with the OSM community (at least, to those who will be present)
* collect street-level data imagery (Lupang Arenda, and the rest of barangay Santa Ana), with the go-ahead from their barangay chairperson
* collect vertical imagery, c/o volunteers Bunny and Ian

More details to be posted as soon as they've been finalized.

**Comment by govvin** [comment]
@govvin Test reply from Telegram channel.

**Comment by govvin** [comment]
The activity is scheduled on July 7, unless it rains.

**Comment by maning** [comment]
Original intent of this ticket is done.  Moving to: https://github.com/OSMPH/papercut_fix/issues/54
