### ISSUE TITLE
Improve roads traced from 1:250K topographic maps

### ISSUE THREAD

**Issue by maning** [OSMPH/papercut_fix#5]
@maning and other previously traced roads from [public domain 1:250K Topographic Maps](http://wiki.openstreetmap.org/wiki/Philippines/Data_sources#AMS_Topo_Maps).  Let's improve the data from Bing imagery.

![screen shot 2016-01-02 at 18 50 34](https://cloud.githubusercontent.com/assets/353700/12074584/c3be29bc-b181-11e5-8581-b2278d1c5549.png)
1. Download the data from this overpass query: http://overpass-turbo.eu/s/dx5
2. Load in JOSM and improve the geometry using Bing/Mapbox imagery, OSM GPS traces or Strava.
3. Update the source tag by including your references i.e. `Bing`.
4. Upload to OSM with the following changeset comment: `Improve roads from previously traced 1:250K topographic maps. See: https://github.com/OSMPH/papercut_fix/issues/5`

**Comment by govvin** [comment]
Just completed the Cebu island data set. If you opt to work in smaller areas, or just the visible map area (bbox), instead of the whole country, use this [query](http://overpass-turbo.eu/s/dwb) instead.

If you're using the JOSM editor, and not using the [ToDo List plugin](https://wiki.osm.org/wiki/JOSM/Plugins/TODO_list), you should!

:smile:

**Comment by maning** [comment]
Fixed a few more.  I deleted roads that are not visible in hires Bing or Mapbox.

**Comment by maning** [comment]
Only 7 ways left but I can't find a good source imagery/traces to verify.  Proposing to **close**.

**Comment by maning** [comment]
Another 1:250K source tag was `AMS 1:250K topomap`.  Same process as above using this query: http://overpass-turbo.eu/s/dUd

**Comment by maning** [comment]
Done!  Finished the last 141 ways.

**Comment by govvin** [comment]
@maning 🚀
