### ISSUE TITLE
Edits by "Lian Spurgeon Las Pinas"

### ISSUE THREAD

**Issue by TagaSanPedroAko** [OSMPH/papercut_fix#50]
@govvin @seav 

This user, "[Lian Spurgeon Las Pinas](http://www.openstreetmap.org/user/Lian%20Spurgeon%20Las%20Pinas) has been mass editing mall expansions around Metro Manila, mostly unverified ones, resulting to the deletion of numerous features that still exist on the ground until proven otherwise on the ground. I already commented on the user's edits, but the user seems to be not willing to explain anything, including sources. A closer look on one deleted [building](https://www.openstreetmap.org/way/244384543/history) beside SM City Manila seems to raise an alarm the user is a sock of "Joey Samson", which has been involved in similar vandalism activity, mostly dealing with future or hypothetical real estate projects which has not been verified or just plain fantasy. I already reported "Lian Spurgeon Las Pinas" to the Data Working Group, citing possible evidence of sockpuppetry.

**Comment by TagaSanPedroAko** [comment]
Connecting with issue #47.

**Comment by TagaSanPedroAko** [comment]
@govvin Asking this to be tagged "laba-kusot-balaw-kula", and marked as an urgent and priority issue

**Comment by govvin** [comment]
@TagaSanPedroAko , if you feel it's appropriate, you should be able to change the label yourself:
![image](https://user-images.githubusercontent.com/5821688/57665992-d248b980-7630-11e9-88a2-b4b2c112a7a2.png)

If you are also offering to help resolve or validate the concern, you can assign it to yourself, too.

> @govvin Asking this to be tagged "laba-kusot-balaw-kula", and marked as an urgent and priority issue

**Comment by TagaSanPedroAko** [comment]
@govvin I don't have the option either to tag issues, so that's why I'm asking you since I mentioned you here.

**Comment by govvin** [comment]
You should consider accepting the invitation we sent you through GitHub, so we can collaborate better here.

**Comment by TagaSanPedroAko** [comment]
User has been given a zero-hour block last week, but seems to have just returned to the older account, and has been blocked again.

**Comment by seav** [comment]
I've reverted a bunch of this user's changesets earlier. The user has been given a 4-day block by the DWG.

**Comment by TagaSanPedroAko** [comment]
User since blocked for about a year. Closing

**Comment by TagaSanPedroAko** [comment]
@seav 

I'm still seeing some edits that haven't been reverted, but possibly just needs verification on the ground. Some examples:

-https://www.openstreetmap.org/changeset/69637848 (and a few other places named "Future Expansion" in Ortigas Center).
-https://www.openstreetmap.org/way/34689589 (involving Harrison Plaza)
-https://www.openstreetmap.org/way/528621142 (involving an additional building on SM City Bicutan)
-https://www.openstreetmap.org/changeset/65542900 (involving DDT Sky Tower, now under construction)
-A few other "future" buildings at Araneta City (e.g. Gateway 2, PNB building expansion)

Looking at those edits, dealing with unconfirmed or even plainly fictional real estate developments, we can call JS (#47) the real estate vandal (though both have also touched public transit stuff). Our latest incident, #60, can be called the creek and highway vandal, but who cares?

**Comment by ianlopez1115** [comment]
Checked the OSM account in question, apparently it no longer exists. Requesting that this ticket be closed for good and that further requests regarding the user be raised at issue #47.

**Comment by govvin** [comment]
Thank you for following-up @ianlopez1115 .  Maybe it's better if we close this ticket after the review and clean-up?

It's unfortunate that other are now expected to clean-up after their mess. :/

**Comment by TagaSanPedroAko** [comment]
@ianlopez1115 @govvin It had been a year, but we still see some of Lian's additions. 

- DDT Sky Tower (can be left as it is, under construction since July 2019).
- Some buildings in Ortigas Center marked as “Future Development”.

**Comment by ianlopez1115** [comment]
@TagaSanPedroAko I'm slowly mopping up the user's contributions for more than a year now. Should be completed on or before Sunday (July 4)

**Comment by ianlopez1115** [comment]
Aside from nodes without tags in the Ortigas and Manila City Hall areas, I can say with confidence that all of the user's edits have been reviewed and cleaned up.

For (hopefully) the last time, I'm requesting that this ticket be closed for good and that further requests regarding the user be discussed at issue #47.
