### ISSUE TITLE
It would be nice to have an OSMph website ...

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#52]
possibly hosted on github, and with content related to FAQs. Like a more user-friendly content from the Philippine mapping conventions wiki page, maybe?

**Comment by seav** [comment]
Let's answer the following questions first (reposted and edited from a discussion back in 2016):

What purpose does the website serve or what do we want the website to do?
Is it to provide a central or easy way for interested parties to contact the OSMPH community?
Is it to *try* to convince the reader that OSM is better than Google Maps?
Is it to highlight the work of the OSMPH community, and list upcoming events?
Is it to provide just a slippy map of the Philippines like the main OSM website?

Also, who is the target audience?
The OSMPH mappers? (Maybe the OSM Wiki pages are better for that especially for documentation.)
Filipinos who are not yet familiar with OSM? (A website would be a good marketing tool for that audience.)

**Comment by govvin** [comment]
Stale issue. Closing.
