### ISSUE TITLE
Proposed mass deletion or redaction: edits around Lemery, San Luis, Santa Teresita, and Taal, with POIs copied from Google Maps

### ISSUE THREAD

**Issue by TagaSanPedroAko** [OSMPH/papercut_fix#58]
This is first reported in #56, but since the latest discovery many of the POIs mapped in what seems to be an organized mapping effort by 5 municipalities in Batangas within Taal Volcano's 20 km radius are copied from Google Maps, I've considered mass deleting many of the POIs added by about 24+ users who mostly refused any attempt to communicate with the OSMPH community. It's still possible to have those remapped, especially on a mapping party to help in post-eruption recovery of the municipalities around Taal Volcano.

**Comment by govvin** [comment]
@TagaSanPedroAko , document your assertions here.

**Comment by DearPaulPH** [comment]
@govvin Remember that any copyrighted data (i.e. Google Maps) must NEVER be into OpenStreetMap data under RA 8293 and its IRR, including the terms and conditions. Moreover, DEARPAUL24 will check for possible cross-matching and removal. Only Mapillary, Bing, Maxar, Esri, Landsat, NAMRIA, DOST are the only authorised sources.

**Comment by TagaSanPedroAko** [comment]
You may check them on Geofabrik Map Compare: http://tools.geofabrik.de/mc/

I strong agree we delete the POIs in question not only for being copied from Google Maps, but they are also placed on odd locations on the map, something kind of typical with GMaps coverage of the Philippines. I still believe those POIs can be better mapped again if they're verified on the ground, and I can't discount a possibility there may be a mapping party held on those areas soon.

**Comment by govvin** [comment]
@DearPaulPH I'm probably one of the last persons you need to remind me of that 😆.

Also, don't forget that local knowledge,  surveys, donated data with compatible licenses are just as valid, too. 

Avoid making the assumption by presenting and documenting your assertions.

**Comment by TagaSanPedroAko** [comment]
@govvin 

I have deleted some of the POIs around Halang and Latag (in Taal), per the evidence I provided in #56.

**Comment by TagaSanPedroAko** [comment]
Deleted a bunch of road names, POIs, and POI names per Map Compare evidence (alongside cleanup of certain POIs), see https://www.openstreetmap.org/changeset/82766031.

@govvin Hope there would be another mapping project for the Taal Lake area since the Taal eruption response and the 2017 MapTVPL project.

**Comment by TagaSanPedroAko** [comment]
Deleted the remaining POIs in Taal, but have got mixed with unrelated edits in Nueva Ecija. Closing for now.
