### ISSUE TITLE
Remove imagery boundaries in OSM

### ISSUE THREAD

**Issue by maning** [OSMPH/papercut_fix#6]
Why should we remove imagery boundaries in OSM:
* Many are **outdated**.
* It **isn't what's on the ground**.  See: http://wiki.openstreetmap.org/wiki/Good_practice#Map_what.27s_on_the_ground
* It should be maintained as a separate database like the [Imagery Coverage Map](https://github.com/OSMPH/Imagery_Coverage_Map) or the [editor-imagery-index](https://github.com/osmlab/editor-imagery-index/)

To edit:
* Run this overpass query: See: http://overpass-turbo.eu/s/dB7
* Review each segment then delete.
* Changeset comment: `Remove imagery boundaries. https://github.com/OSMPH/papercut_fix/issues/6`

**Comment by seav** [comment]
I don't think there is any value. I prefer deleting them.

**Comment by maning** [comment]
I've started deleting imagery boundaries.  Before deletion, I archive the data as [geojson just in case someone needs them in the Imagery Coverage Map repo](https://github.com/OSMPH/Imagery_Coverage_Map/commit/3e60b2ad141f1381615dfc4c0b18683c8c2ca824).  

**Do not do a wholesale deletion** since some nodes/ways maybe part of a valid data.  Check each one first.

**Comment by maning** [comment]
Done!
![screen shot 2016-01-10 at 13 27 03](https://cloud.githubusercontent.com/assets/353700/12220613/ea01274c-b79d-11e5-84f7-a54934619d28.png)
