### ISSUE TITLE
Personal info being added by "NextONE Telecom"

### ISSUE THREAD

**Issue by TagaSanPedroAko** [OSMPH/papercut_fix#61]
The edits by this new user, [NextONE Telecom](https://www.openstreetmap.org/user/NextONE%20Telecom) (obviously a corporate OSM account), is on our radar since March 28, but I'm getting concerned with this one for mass additions of private info, such as the names of homeowners around Tagaytay and elsewhere, and needs immediate cleanup.

I haven't attempted contact with the user for the meantime through changeset comments or private email, but I'll try.

**Comment by DearPaulPH** [comment]
@TagaSanPedroAko Those edits containing private info must be removed since it contradicts the Data Privacy Policies being implemented in accordance to the Data Privacy law.

**Comment by TagaSanPedroAko** [comment]
@DearPaulPH Just to say, you don't need to tell everyone here about the concerned laws 👀. So far OSM policy is concerned, they should not be mapping that at all.

I'll be trying to contact the user, with changeset comments as my preference.

**Comment by govvin** [comment]
I sent the user a direct message, and awaiting a reply.

Also reviewed the user's [edits](http://overpass-turbo.eu/s/Sis) from today and earlier, and [removed](https://www.osm.org/changeset/83008028) the discernible PIIs from the data. 

I'll also request the DWG to purge the same from the database.

**Comment by govvin** [comment]
As of Sun, Apr 12, 8:11 PM, the deleted elements has been redacted from the database.

If there are any more of the same issue, feel free to re-open this ticket.
