### ISSUE TITLE
popup cycle routes by Metro Manila LGUs

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#66]
## Create cycle route relations for each
- [ ] Pasig
  - [ ] review and/or collect updated Mapillary imagery
- [ ] San Juan
  - [ ] review and/or collect updated Mapillary imagery
  - from photos, San Juan's bike lanes are delineated by painted yellow road markings, jersey barriers, traffic cones

> relations will not impact highway features, but will correctly render on relevant cycling tiles

---
per socmed posts:

## Pasig
![image](https://user-images.githubusercontent.com/5821688/83710294-f8356780-a652-11ea-804c-f8747fca097a.png)
source: https://twitter.com/VicoSotto/status/1268112632310927360?s=20

## San Juan
![image](https://user-images.githubusercontent.com/5821688/83710448-56fae100-a653-11ea-8257-0b09a66ef077.png)
source: https://twitter.com/franciszamora30/status/1267277079298465793?s=20

**Comment by maning** [comment]
> Pasig - review and/or collect updated Mapillary imagery

I surveyed and added from Santolan to Manggahan bridge

**Comment by DP24PH** [comment]
**UPDATE** | PH-184 and PH-60/R-5/Ortigas Avenue is now part of the [regional cycle network (rcn) from San Juan City eastward](https://www.openstreetmap.org/relation/8202547), and part of the DOTR plan on cycling network. Likewise, [Pinagbuhatan-Santolan corridor](https://www.openstreetmap.org/relation/8202490) got mapped as well, and may be expanded to include N. Domingo once confirmed by the latest Mapillary imagery.
