### ISSUE TITLE
Edits by "Kent Cydrex Gordo"

### ISSUE THREAD

**Issue by TagaSanPedroAko** [OSMPH/papercut_fix#72]
Just saw some unusual features around N. Samar, mapped by "[Kent Cydrex Gordo](https://www.openstreetmap.org/user/Kent%20Cydrex%20Gordo)" (possibly for some university project, or LGU development plan). Some features involved:

-urban development south of Catarman town proper (complete with streets and boulevards)
-international airport
-expressway between Catarman and Allen (to bypass existing road)

Just sent a message to user, but per edit history, last changeset is 24 days ago.

**Comment by DP24PH** [comment]
@TagaSanPedroAko | Please be advised that the said international airport development plan is not yet listed as part of #BuildBuildBuild projects, and will check further certain highways and roadways with the latest Maxar imagery.

**Comment by DP24PH** [comment]
RECOMMENDATION | The said expressway must be reverted into `proposed:highway=*` tagging scheme to avoid premature rendering into OSM, and any proposed infrastructures (landuse, buildings, etc.) be tagged into `proposed:*=*`. Any further feedbacks?

**Comment by TagaSanPedroAko** [comment]
Have checked existing Maxar, can't see any evidence of clearing.

User appears to be a student or an LGU employee, but needs further investigation. Can ask @govvin for further feedback about handling this and further attempts in reaching into user.

**Comment by ianlopez1115** [comment]
Try contacting him through his social media (Facebook) account and hope that his response is cordial

**Comment by TagaSanPedroAko** [comment]
Suspicious features appears to have been deleted by the user himself. Will close this after second attempt to communicate with user about reasons for those edits.

**Comment by TagaSanPedroAko** [comment]
@ianlopez1115 @govvin Attempt to communicate with user successful. Quoting:

> It is part of the urban development plan of the municiplay since its bound
for its cityhood in the upcoming year.

> May I ask din po kung bakit nireremove yung ibang edits ko ngayon, its
based on the Maxar Sattelite Imagery provided in the database, I am
assigned by the local youth development council to edit or add planned
developments in the area since it has not beed updated yet, and also we
used current drone shots to provide accurate informations. BTW thank you
for you concern.

Case closed, but we still need further communication with user in question. 🚀

**Comment by TagaSanPedroAko** [comment]
Issue solved now, but user still needs help with setting up drone shots for mapping.
