### ISSUE TITLE
DP24 adding his own personal info on map

### ISSUE THREAD

**Issue by TagaSanPedroAko** [OSMPH/papercut_fix#74]
@maning @govvin Just noticed this lately on https://www.openstreetmap.org/changeset/89585107 that @DP24PH himself add some his own private info (as well as floor plan of his home), being hypocritical of his position on mapping private info. Non-obvious, but may need redaction, and user needs to be reprimanded. How bad, the smell of hypocrisy.

**Comment by govvin** [comment]
These side comments are uncalled for.

The objective of this repository is to assist mappers who are unable to fix OSM data issues themselves, and asking the general community for assistance. If the issues involve other mappers, the first attempt is to contact involved parties first, directly (through changeset comments, direct messaging), and preferably privately.

Having seen both of you collaborate on other efforts, I don't see why this could not have been done by messaging each other directly. 

I think there are better ways to address issues like this than reprimands, which is also not encouraged by the community in general. 

I'm closing this ticket for the unnecessary remarks.
