### ISSUE TITLE
Clarifications and review for the roadway/street suffixes upon complaint from fellow dasmarinas-mapper

### ISSUE THREAD

**Issue by DP24PH** [OSMPH/papercut_fix#79]
Upon receipt of OSM DM from @dasmarinas-mapper (which is a valid complaint), an errant user have caught removing such street suffixes in a certain subdivision in Dasmarinas City. Although fixed thru the changeset [94430928](https://osm.org/changeset/94430928), as a fellow OpenStreetMapper (also a volunteer mapper and photographer, Media Ministry servant, content creator/producer/host), I'm also worried about the possibility of edit wars (particularly the roadway/street suffixes), citing the erratic changesets [93147246](https://osm.org/changeset/93147246) and [94216911](https://osm.org/changeset/94216911) that have violated the [OSMPH guidelines on mapping conventions](https://wiki.openstreetmap.org/wiki/Philippines/Mapping_conventions), with this verbatim:

`... names without the suffixes can be a problem when mapping addresses. Try to use the full name as possible (as found on signs or business addresses), but avoid abbreviations.`

Ever since the OSMPH guidelines via OSM Wiki, I myself (@DP24PH) and @dasmarinas-mapper have started collaborating on the validation via #OSMPH #papercut_fix #76 for missing street names (with suffixes), street name validation (with suffixes as possible), barangays, and even the latest validation that requires the resumption of collaboration-based Mapillary imagery, once IATF-MEID have permitted it. Hopefully, your kind response is highly appreciated as I have trying to refrain myself from unnecessary travels to certain places that might have a high-risk of COVID-19-related contamination for safety reasons.

-----
CC: @maning @govvin @ralleon @seav @TagaSanPedroAko

**Comment by TagaSanPedroAko** [comment]
The issue of street name suffixes has been addressed on talk-ph, but I think its up to the user whether to add, keep or remove suffixed on street names. That said, observing the general naming guidelines, I agree we should try to map the full name even where the suffixes are dropped on official signage (usually to save costs if not space), with some possible exceptions. No need to worry about possible edit wars. 

BTW, the user involved in the edits in question appears to be new (though the account dates Dec 2017). Agree we commonly drop "Street" or most suffixes as implied in most situations unless there is possibility of ambiguity, but that doesn't help create useful address info unless we're one of the few countries where the norm is street names being the bare name only.

**Comment by DP24PH** [comment]
Upon reading the _February 2020 talk-ph message_ (including reply from @govvin), it is hereby solved. Hence, street name review will continue even if this ticket is closed, and thank you very much, @TagaSanPedroAko, for your valued input.

More info: https://lists.openstreetmap.org/pipermail/talk-ph/2020-February/006543.html
