### ISSUE TITLE
Edits by "Darryl Cortez"

### ISSUE THREAD

**Issue by TagaSanPedroAko** [OSMPH/papercut_fix#80]
I think this guy's ([Darryl Cortez](https://www.openstreetmap.org/user/Darryl%20Cortez)) edits has been raising suspicions reminding me of those behind #56 / #58 in Batangas, and another newbie from Lipa City. The user is not a month old, but has made 1000+ edits, many referring to the PARA ride-hail app, and many are just possibly copied from GMaps.

**Comment by ianlopez1115** [comment]
Another [user](https://www.openstreetmap.org/user/JPBaje) may be doing something similar, but the user is currently focused on Pagsanjan and San Pablo City in Laguna.

I suggest that a member of the OSMPH Community (could be me or not) communicate with the team behind PARA SAFE (as the app is currently called) asking them if they have been contributing to the map and guide them to follow the [OSM Organized Editing Guidelines](https://wiki.openstreetmap.org/wiki/Organised_Editing_Guidelines) and not to copy data from Google Maps should they answer in the affirmative.

**Comment by Timmy-Tesseract** [comment]
There's also [Abby Oavad Tagum](https://www.openstreetmap.org/user/Abby%20Oavad%20Tagum) doing the same around Tagum City. 

I've checked about 10 nodes that were added and every single one was verifiably copied from Google Maps. Also no replies to changeset comment. 

If this is related to PARA SAFE, contacting them sounds like a good idea. Other than that, should we report the users to DWG? Given the big number of changesets, is anyone here capable of reverting hundreds of changeset at once?

**Comment by Timmy-Tesseract** [comment]
I've just sent an email to DWG reporting the additional users including two more that I just discovered today. 

For overview here's a list of all accounts that have been reported so far:
Abby Oavad Tagum
ortegajovan41
Darryl Cortez
JPBaje
Dhadz

**Comment by TagaSanPedroAko** [comment]
It's very disappointing we had guys like this slip through our fingers. I also have no clue why people like them doing this. Lockdown blues? Just because you can't just go out and map due to quarantine restrictions is not an excuse to copy from GMaps. They can still map their area within their reach under existing quarantine protocols, and not resort to illegal copying of map data. It's not only the users in question could get into trouble with the Intellectual Property Code, but also the Foundation as a whole for hosting map data that violate Google's and the developers of Para SAFE for leading a mapping activity that unknowingly allowed to infringe on Google's copyright. Have anyone communicated with the app developers?

To me, GMaps coverage of the Philippines tend to be worse in lots of places, and some POIs are in very odd locations. It's not uncommon several POIs are kilometers away from where they should be.

**Comment by TagaSanPedroAko** [comment]
@Timmy-Tesseract @ianlopez1115 Provided this incident (and other similar cases reported) happened during lockdown, I would think the present quarantine restrictions preventing most forms of travel is driving this kind of mapping, because you can't just go outside of your barangay or city/municipality without having a quarantine pass or you're not authorized to. But again, that's no good reason to do Illegal copying from other maps. What's really Para SAFE, and what's their purpose for mapping here?

**Comment by TagaSanPedroAko** [comment]
I'm currently more busy mapping in Canada (mapping new bus routes in Edmonton, addition of turn lanes, speed limits and land use, general cleanup) but I'm able to fix or delete some POIs in Batangas City that Darryl have added. Some are completely suspicious, while other verified from my previous trip last 2019. POIs in question are in Pallocan (Pastor Village/area around SM Batangas); There are some in Kumintang and Calicanto.

**Comment by govvin** [comment]
WRT Para Safe app, I wrote to them a few weeks back, and here are some screenshots of the emails they got. It took a few days to get the initial answer, but they were, at least, responsive:

#### They acknowledge they are using OSM and don't disavow the personnel adding data on their behalf:
![image](https://user-images.githubusercontent.com/5821688/116167219-5c14c300-a732-11eb-8ead-a05142e6019a.png)

#### They acknowledge they might be using copyrighted material, and claim that they will desist from doing so again:
![image](https://user-images.githubusercontent.com/5821688/116167245-6c2ca280-a732-11eb-983b-de0ceaa2708f.png)

#### They claim they now have guidelines in place, to avoid use of copyrighted material and that their people will only add data based on "available resources and their knowledge and familiarity of their community. "
![image](https://user-images.githubusercontent.com/5821688/116167543-fd037e00-a732-11eb-9927-d658e3a0581f.png)

It's been several weeks since the last response, and I think that's sufficient time for them to clean up after their edits. If no action has actually been made, someone can ask the DWG to purge those suspicious edits.

**Comment by TagaSanPedroAko** [comment]
@govvin I've been able to find out what PARA SAFE really is after finding an ordinance by the Batangas City government dating late 2020 exempting the company from part of the LGU's 2019 traffic ordinance dealing with PUVs. Also, the areas being covered by most of the user's edits, namely, Batangas City, Lipa, Cauayan and San Fernando (La Union), also happened to be cities where PARA have or may have been serving. My previous assumptions PARA is a ride-hail service have been correct, though this one having an app where you can hail a tricycle.

I've been making some edits around Batangas City lately, trying to clean the user's mess, particularly suspiciously located POIs. I've deleted some and kept others basing from what I saw on my 2019 trip and previous trips.

@Timmy-Tesseract As for the similar cases, they mostly appear to be unrelated with this case. JPBaje have also mapped in Lipa, but is unrelated since this user moved to map parts of southern Laguna (Alaminos, San Pablo, and Calauan) and then moving to map part of Enugu in Nigeria (last place edited before their account was blocked since I followed up their case to DWG via email).  That said, I can't discount this could be also an editor for PARA given some edits involved areas that have been edited by Darryl, but there is little to no evidence to prove he's working for PARA and he had refused to communicate.

Also from what I saw in the 2020 ordinance in regard to PARA, I've also previously saw edits by another company being dealt with in that  said ordinance, EZYGO, an app developer based in Batangas City. A corporate OSM account have also edited parts of Batangas City, adding some POIs and their main office, though unlike the edits by Darryl, are mostly based on local knowledge.

**Comment by TagaSanPedroAko** [comment]
@govvin It should help we ask the PARA SAFE team set up a project page here and on the wiki (like with Grab and Apple), should they do a large mapping project to comply with OSMF's Organised Mapping Guidelines.

**Comment by govvin** [comment]
@TagaSanPedroAko , of course I asked them, but there had been no response since the last exchange in March.

**Comment by TagaSanPedroAko** [comment]
I've mass reverted some of the user's edits in Batangas City and Lipa, and I've already called in the DWG by email to revert the remainder.

**Comment by TagaSanPedroAko** [comment]
I've been able to find the user's heat map (https://yosmhm.neis-one.org/?Darryl%20Cortez), which shows the areas where he has edited. Basing on the map, much of his activity is concentrated around northern La Union (particularly around San Fernando) and Cauayan. Most of his edits in Batangas have been reverted, except patches in Lipa, Padre Garcia and Batangas City. I can revert the remaining ones in Batangas while awaiting the revert.

**Comment by TagaSanPedroAko** [comment]
Just reverted the remaining ones around Lipa and surrounding municipalities. Darryl has not only edited Lipa; there are also POIs added around Ibaan (along the provincial road from Lipa), San Jose (along Route 4), and Padre Garcia (primarily around Poblacion, Batangas-Quezon and Rosario Bypass Road). There are a few as well in barangay Dita in Cuenca, along Route 433. Nakakasura niya!

**Comment by TagaSanPedroAko** [comment]
Ni-revert ko na ang natitira niyang edit sa Batangas. Ngah, nakakainit ng dugo! L***** na Darryl! Paniguradong kopya, lalo't GCQ pa ngayon at mahirap bumyahe.

**Comment by TagaSanPedroAko** [comment]
@govvin Should Darryl be brought to court? I would consider this serious IP Code violations.

**Comment by Timmy-Tesseract** [comment]
> 
> It's been several weeks since the last response, and I think that's sufficient time for them to clean up after their edits. If no action has actually been made, someone can ask the DWG to purge those suspicious edits.

I've send a request for that together with side-by-side screenshots of copied POIs for each individual user. This is the reply that I received from DWG:

> 
>I set an 0-hours block for each user you report. They will see the warning when they login.
>
>Frankly speaking, it is quite hard to accuse someone from copying POI from other maps. A block is quite a serious response for misbehave.
>
>Let wait and see if they have any further no so good edit after they login again.
>Feel free to drop a message to Data Working Group.
>

Unrelated to this e-mail a different member of DWG seems to have done a complete revert for [JPBaje](https://www.openstreetmap.org/user_blocks/4899). 

I'm a bit confused why in that case evidence was sufficient but for the other 4 users it wasn't.

**Comment by ianlopez1115** [comment]
> @govvin Should Darryl be brought to court? I would consider this serious IP Code violations.

For me, the IP holder (Google or its PH representative/s) should be taking the covered users to court, not the OSM PH community or people that are part of it in this instance.

**Comment by TagaSanPedroAko** [comment]
I've just completed the reverts around Batangas, trying to take care of those that remain, except those I have verified to be existing since my 2019 trip.

@ianlopez1115 @govvin  It's still possible to have the matter brought into the attention of the IP holders (Google or Google PH), telling the mappers in question (particularly Darryl) have done serious violations of Google's Terms of Use and Philippine copyright law (IP Code of 1999); this may or may not lead into a court case against those involved. Same can be done with JP Baje.

To me, this case of mass POI copying still seems to be driven by the present ECQ and GCQ. Again, is this possible this and the other similar cases are due to lockdown blues?

**Comment by TagaSanPedroAko** [comment]
Now there has been ongoing developments regarding the issue with PARA mapping activities in OSM, thanks to one editor who disclosed affiliation with PARA and helped in addressing some of the issues such as with third-party data providers working for PARA, we can close this ticket and have all newer developments covered at #83.
