### ISSUE TITLE
Contributor is adding PSA boundaries to OSM

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#81]
This issue was first [reported](https://t.me/OSMph/17116) by Eugene in the Telegram hangout. 

OSMCHA filter of changesets citing "Philippines (PHL) Administrative Boundary Common Operational Database (COD-AB), NAMRIA, PSA" as source: https://osmcha.org/?aoi=48f14d28-7be9-41e8-a12f-48f1af660523

- [x] for further review  
- [x] see if contact with mapper has been made
  - [x] 5/18 [changeset comment](https://www.openstreetmap.org/changeset/100947120) left by Eugene
  - [x] 5/19, [DM](https://user-images.githubusercontent.com/5821688/118742505-1ce61780-b883-11eb-8c3c-31fc749f1f5b.png) sent by GOwin
- who will take point?
  - [x] propose a rollback plan (possibly similar to what we learned from #67 )

**Comment by seav** [comment]
Added a comment on one of the user's changesets: https://www.openstreetmap.org/changeset/100947120

**Comment by seav** [comment]
I did a spot check with one CamSur municipality and I can confirm that the added boundary matches the IMTWG dataset.

**Comment by govvin** [comment]
I also sent a [DM](https://user-images.githubusercontent.com/5821688/118742505-1ce61780-b883-11eb-8c3c-31fc749f1f5b.png). Let's wait for the user to respond before proceeding with next steps.

**Comment by govvin** [comment]
The contributor has [responded](https://user-images.githubusercontent.com/5821688/118901148-29cb3f80-b945-11eb-945b-b360ff5fb31d.png) positively, and is willing to help resolve the issue. 

I already asked whether the rollback is something they can do on their own, or would need assistance or advice. The user was invited to join the ticket, or the Telegram group, to co-ordinate the resolution of this ticket.

**Comment by govvin** [comment]
User [indicated](https://user-images.githubusercontent.com/5821688/118906935-42d9ed80-b951-11eb-9d63-95f2907e7733.png) their willingness to remove affected elements, or attempt a roll-back, on their own.

**Comment by govvin** [comment]
User is attempting roll-backs but is now [asking for assistance](https://user-images.githubusercontent.com/5821688/118914161-52f7ca00-b95d-11eb-8fa7-563f99bc634a.png). 

Is anyone willing to take point for this ?

**Comment by Timmy-Tesseract** [comment]
I just tested reverting a few of the changesets in questions (without uploading) and there were only very minor conflicts. As long as reverting happens in correct reverse order there shouldn't be any big issues. 

But for boundaries that were newly added it might be better if we just delete them manually as the mapper also did a lot of river tracing within the same changesets.

**Comment by ianlopez1115** [comment]
Consider reverting the most recent changesets first then work your way towards less recent work.

I'm willing to revert affected areas in and closest to Naga City.

**Comment by govvin** [comment]
@ianlopez1115 , looks like it's mostly around Naga

>![image](https://user-images.githubusercontent.com/5821688/118926655-42524e80-b973-11eb-819d-86b1853bc8f2.png)
http://overpass-turbo.eu/s/17xv

~~We probably should compile a check list of municipal boundaries that needs review, so we could avoid stepping on each other toes. I'm reviewing the data now.~~

**Comment by govvin** [comment]
Looks like it's the following relations that has to be reviewed. If you successfully completed a roll-back of these elements, please add a tick mark. You're welcome to leave any comments, too.

- [x] Santa Elena, https://osm.org/relation/12552464
- [x] Capalonga, https://osm.org/relation/12551398 
- [x] Jose Panganiban, https://osm.org/relation/12537567
- [x] Paracale, https://osm.org/relation/3739699
- [x] Labo, https://osm.org/relation/12552483
- [x] Vinzons, https://osm.org/relation/12442284
- [x] Daet, https://osm.org/relation/3739990
- [x] Mercedes, https://osm.org/relation/12441960
- [x] Lupi, https://osm.org/relation/12589435
- [x] Ragay, https://osm.org/relation/12582956
- [x] Tigaon, https://osm.org/relation/12599567
- [x] Sagñay, https://osm.org/relation/7750022 
- [x] Ocampo, https://osm.org/relation/12587208
- [x] Pili, https://osm.org/relation/12566059
- [x] Minalabac, https://osm.org/relation/12568853
- [x] Milaor, https://osm.org/relation/12566017
- [x] San Fernando, https://osm.org/relation/12568899
- [x] Gainza, https://osm.org/relation/12556094
- [x] Canaman, https://osm.org/relation/12561866
- [x] Naga, https://osm.org/relation/3084673
- [x] Bombon, https://osm.org/relation/12561990
- [x] Magarao, https://osm.org/relation/12561910
- [x] Albay, https://osm.org/relation/1504625

Also, these orphaned ways that aren't part of any relations but the user has tagged as `boundary=administrative`
- [x] https://osm.org/way/932263375
- [x] https://osm.org/way/916911610
- [x] https://osm.org/way/932263376
- [x] https://osm.org/way/456583083

And these should be reviewed last, after the municipal boundaries has been reviewed:
- [x] Camarines Norte, https://osm.org/relation/1504550
- [x] Camarines Sur, https://osm.org/relation/1504551
- [x] Bicol Region, https://osm.org/relation/3561455
- [x] Calabarzon, https://osm.org/relation/1552120
- [x] Quezon, https://osm.org/relation/1504500

Please double-check if there's anything else that was missed.

**Comment by govvin** [comment]
FYI, the local Kaart team will be supporting this effort, and will devote some cycles towards resolving this issue asap.

**Comment by Timmy-Tesseract** [comment]
Finished tasks, ticked off in above list:
- [x] Lupi
- [x] Ragay
- [x] Tigaon
- [x] Sagñay
- [x] Ocampo
- [x] way 932263375
- [x] way 916911610
- [x] way 932263376
- [x] way 456583083

Newly finished tasks:
- [x] Mercedes

Additional relations missing on list:
- [x] Basud, https://www.osm.org/relation/12441968
- [x] San Lorenzo Ruiz, https://www.osm.org/relation/12441969
- [x] Talisay, https://www.osm.org/relation/12441971

**Comment by VMPanes** [comment]
Completed these two tasks:
- [x] Paracale, https://osm.org/relation/3739699 
- [x] Vinzons, ~~https://osm.org/relation/12442284~~ restored https://osm.org/relation/3739722/

**Comment by govvin** [comment]
Great progress, everyone! Thank you for your help. Also, it should be noted that the mapper also contributed to reverting some of their own edits. 

![image](https://user-images.githubusercontent.com/5821688/119244166-40b99e00-bba0-11eb-9c14-480d3ae7f09e.png)

Last night @seav mentioned that the grayscale Mapnik layer is not updated as often as the mainstream layers, and I confirm that it should be possible to "recycle" old elements (that's a tip we previously learned from @ianlopez1115 ) to restore the old geometry, like so:

![image](https://user-images.githubusercontent.com/5821688/119244208-c5a4b780-bba0-11eb-8e3a-ff4639d8cf13.png)

The end-point for grayscale Mapnik tiles is : `https://tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png`

**Comment by govvin** [comment]
Removed adjustments made by c4rlo on the following elements, and restore old geometry based on Mapnik grayscale
- [x] w306449382
- [x] w28085125
- [x] Camarines Sur, https://osm.org/relation/1504551
- [x] Camarines Norte, https://osm.org/relation/1504550
- [x]  Bicol Region, https://osm.org/relation/3561455
- [x] Calabarzon, https://osm.org/relation/1552120
- [x] Quezon, https://osm.org/relation/1504500

Additional features not found in original tasking list:
- [x] Del Gallego  r11210202

**Comment by VMPanes** [comment]
Completed these three items from the list:
- [x] Daet, https://osm.org/relation/3739990
- [x] San Lorenzo Ruiz, https://www.osm.org/relation/12441969
- [x] Talisay, https://www.osm.org/relation/12441971

**Comment by govvin** [comment]
Awesome job folks! Kudos to @seav @ianlopez1115 @Timmy-Tesseract @VMPanes for all your help! We also acknowledge the efforts made by c4rlo to rectify the issue.

Unless there's any more outstanding issues, this ticket seems complete.

If you can, please review the area with your favorite QA tools, to identify any issue we might have missed - and fix them, if possible, before we close this ticket.

**Comment by govvin** [comment]
Again, good job, folks, and thank you very much for helping out.

Closing this ticket now, and c4rlo sends their thanks to the local community, for helping resolve the concern.

![image](https://user-images.githubusercontent.com/5821688/119294929-2b1fa380-bc88-11eb-9359-c3ff7b300e36.png)
