### ISSUE TITLE
OSM contributions by Para Apps, Inc.

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#83]
This ticket consolidates multiple concerns identified with several OSM accounts, and the editing behavior of users identified (or believed) to be working with or for [Para Apps Incorporated](https://paraappsinc.com/), developer of the following apps that uses OSM data

- Para - tricycle hailing app in the Philippines
- Para 9JA - re-branded app for market in Enugu Nigeria
- CITRANSCO - taxi app

As early as January, several members of the local community has attempted to reach out directly to these accounts, or through their corporate contact channels.  

On 2nd July, the user account "Jan Rei Gallardo", was asked to relay to their team and supervisors for an online meeting with interested parties from the LoCo, to discuss the concerns below. For this reason, I ask that we defer any specific actions until they have been given time to consider this opportunity to present or elaborate on their processes.

## Community concerns

- [x]  possible copyright infringement / TOS violations (Jherome's recent [email](https://lists.openstreetmap.org/pipermail/talk-ph/2021-July/006773.html), Timmy's email in [talk-ph](https://lists.openstreetmap.org/pipermail/talk-ph/2021-July/006791.html)'s comparing POIs between OSM and a copyrighted map)
- [x]  [disregard for the organized editing guidelines](https://lists.openstreetmap.org/pipermail/talk-ph/2021-July/006788.html), raised by Andy Townsend (Note: Para App, Inc was advised of these guidelines in [2nd March 2021](https://user-images.githubusercontent.com/5821688/124338832-8e341c80-dbdc-11eb-9847-8d37c1143592.png))
- [x] [suspicious edits in Nigeria, by same user(s)?](https://lists.openstreetmap.org/pipermail/talk-ph/2021-July/006784.html)

##  OSM uid/usernames 
Users who disclosed their affiliation with Para (in DMs), mention of "Para", "ParaApp", "Para Safe" in changeset comments, or believed likely to be associated with Para Apps, Inc. 
>Those marked with :heavy_check_mark:  are confirmed mappers for Para Apps.

- [x]  `13550004` aka Jan Rei Gallardo, Devinbryant (affiliation disclosed in DMs)
- [x]  `12064278` aka JPBaje (blocked by DWG, all changes reverted on 2021-05-01)
- [x]  `12473016` aka Darryl Cortez (Inactive since DWG warning block. see #80 )
- [x]  `12768683` aka Dhadz (inactive since DWG block. According to Para, operated by the same person behind "Darryl Cortez" account)
- [x]  `12472402` aka Abby Oavad Tagum (received multiple blocks by DWG; "shared account" between multiple users according to Para)
- [x]   `8721425` aka ortegajovan41 (has been given warning block by DWG;  continued with editing unrelated to Para after the block)
- [x]  `12954667` aka Jovani Jacalne (confirmed by Para Apps, Inc. as operated by their franchisee)
- [x] `12064265` aka Kei Garavillas (disclosed by Para Apps)
- [x] `12472460` aka Ashley Kaye Lim (confirmed by Para Apps, Inc. as operated by their franchisee)

## Suggested courses of action by Para Apps
- [x] Work with the community and/or DWG to identify and remove copyrighted edits.
- [ ] Create and maintain a page on the [OSM Wiki](https://wiki.osm.org) as stated in the OSMF's [Organised Editing Guidelines](https://wiki.osmfoundation.org/wiki/Organised_Editing_Guidelines) and then added to the [list of organised editing activities](https://wiki.openstreetmap.org/wiki/Organised_Editing/Activities). The wiki page should have an up-to-date list of OSM accounts that map as part of Para's mapping activities, whether internal or third-party contractors.
- [ ] Decide on a hashtag to identify changesets as being under Para Apps' scope, and instruct mappers to use the hashtag when editing. Example: `#para` or `#paraapp`.
- [ ] Improve training and onboarding of mappers, whether internal or third-party contractors. Also instruct mappers to indicate their affiliation with Para Apps on their OSM profile. The local community can help or assist with the training if needed.
- [ ] Improve QA processes so that this whole issue will not be repeated. The idea is that volunteer mappers shouldn't have to look after or clean up after edits done by mappers under Para Apps. Para Apps can consult with Mapbox or Grab PH if needed.

------

Feel free to add any additional observations ,or findings you've made related to these concerns.

**Comment by Timmy-Tesseract** [comment]
Thanks for compiling all of this. 

Just some small additions:

* [ ]   `13550004` aka Jan Rei Gallardo, Devinbryant (affiliation disclosed in DMs)

* [x]   `12064278` aka JPBaje (blocked by DWG, all changes reverted on 2021-05-01)

* [ ]   `12473016` aka Darryl Cortez (received initial block by DWG, has not been active since, see [Edits by "Darryl Cortez" #80](https://github.com/OSMPH/papercut_fix/issues/80) )

* [ ]   `12472402` aka Abby Oavad Tagum (received multiple blocks by DWG)

* [ ]   `12768683` aka Dhadz (received initial block by DWG, has not been active since)

* [ ]    `8721425` aka ortegajovan41 (ignored initial block by DWG, did some edits unrelated to Para in the past as well as after block)

**Comment by govvin** [comment]
@Timmy-Tesseract , thank you for the details. I've updated the original post and incorporate them.

Btw, here's an interesting tidbit I found from various news articles:

- It's been reported that name of the COO of Para App is a certain Jovan C. Ortega. I wonder how this person is related to the user account "ortegajovan41"?

**Comment by Timmy-Tesseract** [comment]
> 
>  It's been reported that name of the COO of Para App is a certain Jovan C. Ortega. I wonder how this person is related to the user account "ortegajovan41"?

This only raises further question about their innocence. Their [commitment not to use copyrighted sources](https://github.com/OSMPH/papercut_fix/issues/80#issuecomment-827227257) dates to March 2. The questionable edits by user ortegajovan41 were made on April 16. I'd expect that the COO of a company would have been informed about such an issue.

**Comment by govvin** [comment]
Since their last message, with the subject ["We're sorry"](https://imgur.com/ml0IR2e), I haven't receive any more messages from "Jan Rei Gallardo". That was three days ago.

I wrote them a follow-up message, this time stating when I expect to hear back from them, so that we may proceed with determining how to resolve this concern. Message below:
![Imgur](https://imgur.com/Gaj7tvb.png)

I believe that we have given sufficient advance notice last time for a simple meeting, but thought it's courteous to extend it a few more days.

**Comment by govvin** [comment]
I got a response, and the purported email address of their CEO
![image](https://user-images.githubusercontent.com/5821688/124443401-3948ff80-ddb0-11eb-8aa4-7b12e525532b.png)

I will send the same message I posted earlier, cc'ing the OSM-PH address.

**Comment by Timmy-Tesseract** [comment]
Just found another one: [Jovani Jacalne](http://hdyc.neis-one.org/?Jovani%20Jacalne)

Noticed him due to some duplicated POIs in Tagum, but he was also active in Tanauan and Enugu.

**Comment by TagaSanPedroAko** [comment]
And they’re also adding POIs in Santo Tomas City. Lots of those are tagged shop=general (intended for general merchandise stores, but some of the Para editors have been using this tag instead of more specific tags). Also pinging in: @ianlopez1115

**Comment by Timmy-Tesseract** [comment]
Additional mapper as disclosed by Para: [Kei Garavillas](http://hdyc.neis-one.org/?Kei%20Garavillas)

Also Dhadz seems to be a sockpuppet of Darryl Cortez, created after community started questioning edits on his first account.

Jovani Jacalne was not confirmed yet, but editing pattern as well as timeframe is too similar to be unrelated. 

In regards of the needed reversions, the only personal edits that were made by any of these accounts seem to be edits by ortegajovan41 before and after 2021-04-16.

**Comment by seav** [comment]
I've added a section under this ticket's description: "Suggested courses of action by Para Apps". Please review and feel free to edit/add items.

**Comment by seav** [comment]
I would also like to note here (for the record) that I looked at some of the POI edits in Parañaque and they often duplicate existing POIs.

**Comment by govvin** [comment]
- [x] The recording of today's meeting is temporarily available [here](https://youtu.be/7FX9hsJe21I). It  will be removed as soon as this ticket is resolved.

**Comment by govvin** [comment]
I propose the following:

## Proposed actions for OSM-PH
- Get a written confirmation (by email) of this course of action with Para apps,  and request DWG to purge all edits made by the identified accounts from Jan 1 2021 - to July 7, 2021 (as agreed during the 7/7 meeting.)
  - Share this ticket, and associated links to DWG for reference
- Ask DWG to block the following uids: `12768683`, `12472402`
- Encourage Para Apps to participate in the community channels, for peer-to-peer support.

**Comment by TagaSanPedroAko** [comment]
Just found another possible Para mapper: [Ashley Kaye Lim](https://www.openstreetmap.org/user/Ashley%20Kaye%20Lim-%20LIPA)

She edited entirely within Lipa and Padre Garcia, specifically along Route 435 Batangas-Quezon and east of downtown Lipa and barangays Munting Pulo and San Isidro, and her edits are at the same timeframe as Darryl and JP. Most of her POI’s are more or less also copied from GMaps.

**Comment by govvin** [comment]
As of 28th July, DWG (specifically, Andy Townsend) confirmed that they are working on this.  The DWG ticket refence is `2021070910000065`.

**Comment by govvin** [comment]
As of 29th July, according to the email from DWG, the edits made by the identified users has been reverted by them.  The complete redaction from the database is scheduled to happen in the next few days.

The public link of the video recording  of the meeting has been taken down. Further access to the video may be requested, and will be considered on a case-by-case basis.

For all intents and purposes, this issue is resolved.

**Comment by TagaSanPedroAko** [comment]
@govvin Just noticed this user lately, having tracked down some POIs around Padre Garcia that appears to be from GMaps as well: [Maryerick](https://www.openstreetmap.org/user/Maryerick). I would think this could be also editing for Para as well, just before Ashley surfaced.
