### ISSUE TITLE
Vandalism in West Philippine Sea

### ISSUE THREAD

**Issue by Timmy-Tesseract** [OSMPH/papercut_fix#85]
Just found a mapper removing all except chinese names from various disputed reefs and islands. Will file a report at DWG.

Here's the changeset link if someone would like to revert already:
https://www.openstreetmap.org/changeset/112370537#map=7/8.364/115.323

**Comment by govvin** [comment]
@Timmy-Tesseract Good catch, Timmy! Thank you.

**Comment by Timmy-Tesseract** [comment]
Funny... just half an hour after I did a minor role modification for Kalayaan boundary relation this happened:
https://www.openstreetmap.org/changeset/112865671

Will report this one as well.

**Comment by DP24PH** [comment]
EXTRA INFORMATION

It is confirmed vandalism that affects the boundary relation of the Palawan province/MIMAROPA region. I'll step in for the restoration effort to restore the affected boundary relation tomorrow.
